### ISSUE TITLE
Excel & Power Point files corrupted

### ISSUE THREAD

**Issue by OSXGroupFL** [misterunknown/ifm#100]
I have tested with multiple browsers. When .xlsx files are downloaded they are corrupted and can not be opened. I have SCP files down after upload and they are fine.

**Comment by misterunknown** [comment]
I can't reproduce this error. Could you verify the problem on https://ifmdemo.gitea.de?

Cheers,
Marco

**Comment by OSXGroupFL** [comment]
ok it works on the demo without issue. My apologies.

**Comment by misterunknown** [comment]
Well, there are multiple possible explanations. For example some inconveniant PHP options... Do you see anything in the error log?

**Comment by misterunknown** [comment]
You can also test your instance via curl. Just try to download your file like this:
```
curl -o YOURFILE.xlsx "https://YOURURL/?api=download&dir=YOURDIRECTORY&filename=YOURFILE.xlsx"
```
And see if it is broken or not.

**Comment by OSXGroupFL** [comment]
I have figured out that I broke the script trying to modify the top menu. Is there an easy way to remove option from that menu?

**Comment by misterunknown** [comment]
Which menu option do you mean? You should be able to disbable the menu options in the [configuration](https://github.com/misterunknown/ifm/wiki/Configuration).

**Comment by OSXGroupFL** [comment]
I have a very specific use case and management wanted Search removed and the Drop down at the far right along with the ability to rename files during upload. I have it all working again correctly now. Thank you for your help.
