### ISSUE TITLE
Parse error: syntax error, unexpected ':' in /public_html//ifm-master/ifm-master/src/main.php on line 173

### ISSUE THREAD

**Issue by nk932714** [misterunknown/ifm#101]
Parse error: syntax error, unexpected ':' in /public_html//ifm-master/ifm-master/src/main.php on line 173

**Comment by misterunknown** [comment]
The `src` directory is only for development. The `compiler.php` compiles all necessary files from `src` and generates a single `ifm.php` file, which you can find in the root directory of this repository.

**Comment by nk932714** [comment]
Thank you. @misterunknown
