### ISSUE TITLE
Feature Request: copy file address to clipboard

### ISSUE THREAD

**Issue by guzzisti** [misterunknown/ifm#102]
I've recently discovered IFM and i`m really pleased about the ease of use.
I am missing one single feature (at least i couldn`t find it):
i want to copy the URI of a file to the clipboard to paste it somewhere else.

**Comment by misterunknown** [comment]
[Done](https://github.com/misterunknown/ifm/commit/f1afbaee4da103eeb083b52b81ffc5252b05ac86)
