### ISSUE TITLE
Read-only/guest mode

### ISSUE THREAD

**Issue by hfel** [misterunknown/ifm#103]
Hi! I wonder if it would be possible to include a mode where the file manager is visible by default with only read access, with the option to sign in as a user with heightened privileges.

**Comment by misterunknown** [comment]
Not at the moment. You can have two instances with different configurations as a workaround. I'll take a look at the code, but I guess a guest mode would require some work. I have to think about it a bit.

**Comment by misterunknown** [comment]
Providing a guest mode is not easy to do. It would be possible but would require quite some work to do. Therefore I concentrate more on the multi-user features which are under development, but not expected to be ready this year. I close this issue for now; keep track of #89 if you want to get updates on the multi-user feature.
