### ISSUE TITLE
small issues in "copy link" feature

### ISSUE THREAD

**Issue by guzzisti** [misterunknown/ifm#104]
There's a small bug in the copy link feature:
if i place ifm in a subfolder, the folder is missing in the copied uri. For example:
`domain.com/subfolder/ifm.php`
when copying a link, its just `domain.com/myfile.name` instead of `domain.com/subfolder/myfile.name`.

Additionally when using a custom root folder, the copied link is `domain.com/undefined`. All other features work well with custom root folders.

Would be nice if you could have a look at this.

**Comment by misterunknown** [comment]
> if i place ifm in a subfolder, the folder is missing in the copied uri. For example:
> `domain.com/subfolder/ifm.php`
> when copying a link, its just `domain.com/myfile.name` instead of `domain.com/subfolder/myfile.name`

This is fixed now.

> Additionally when using a custom root folder, the copied link is `domain.com/undefined`. All other features work well with custom root folders.

Unfortunately it's not possible to reliable determine if a custom `root_dir` is accessible via the webserver, so I disabled the copy link function if a custom `root_dir` is set, for now.

**Comment by guzzisti** [comment]
thanks for the quick solution. I'm fine with the root_dir workaround, i think it's better to disable a function rather then have it behave false. Issue closed.
