### ISSUE TITLE
Feature Request: copy link and root_dir

### ISSUE THREAD

**Issue by stenioaraujo** [misterunknown/ifm#107]
As stated here https://github.com/misterunknown/ifm/issues/104#issuecomment-445807144, the 'copy link' button is hidden when `root_dir` is set.

I have noticed that, although the default behavior of the Download button is to send a `POST` request to the server, the same request works when sent as  `GET`.

Example: 

```
curl -o file.zip "http://localhost:8080/?dir=myfolder&filename=file.zip&api=download"
curl -o myfolder.zip "http://localhost:8080/?dir=&filename=myfolder&api=zipnload"
```

Maybe the 'copy link' button could have that format of URLs when `root_dir` is enabled.

I know it is nothing compared to `http://localhost:8080/myfolder/file.zip`, but it adds the convenience factor of having easy access to the link. Besides, it allows for copying a link to download a whole folder :)

off-topic: IFM is great!

Sorry if this is a repeated issue.

**Comment by misterunknown** [comment]
You're right... I guess I can get rid of the hidden form completely, as a POST request doesn't add any value. I'll do some tests tomorrow, and keep you updated.

**Comment by misterunknown** [comment]
I just created a branch, but still have some work to do, as it does not work in all of my testcases, yet.

**Comment by misterunknown** [comment]
Ok, I merged the branch. Should be ok now. Please let me know, if you find any flaws.

**Comment by stenioaraujo** [comment]
I just tested. It is exactly what I was expecting it would be :) Great work.

- [x] Allow copy link when `IFM_ROOT_DIR` is set.
- [x] Allow copy link when `IFM_ROOT_DIR` is not set.
- [x] Zip folders when `IFM_ROOT_DIR` is set (+1).
  - Since the httpd server doesn't have access to the folder defined by `IFM_ROOT_DIR`, I think that is a great approach, to allow PHP to deliver the folder instead.

I noticed that the default language is now German? Was that intended? I don't see a problem with it since `IFM_LANGUAGE` is easy to set.

Again, Thank you.

If there is any more testing you would like me to do, just let me know.

**Comment by misterunknown** [comment]
> I noticed that the default language is now German? Was that intended? I don't see a problem with it since `IFM_LANGUAGE` is easy to set.

Oh, no, that was by accident... I just fixed that.

Apart from that I guess everything should work, so there is nothing particular to test. Anyway, if you notice any bugs in daily use, just let me know.

Cheers,
Marco
