### ISSUE TITLE
[i18n] Add Brazilian Portuguese translation

### ISSUE THREAD

**Issue by stenioaraujo** [misterunknown/ifm#111]
I am a big fan of IFM and I would like to contribute with the Brazilian Portuguese translation for it. I think it would be a great plus for the app.

**Comment by misterunknown** [comment]
Hint: I just pushed a commit, which fixes the assignment of the default language. So you can use the IFM exclusively with portuguese localization:
```
./compiler --language=pt-br
```
This works even if `$config['language']` references an absent language.

**Comment by misterunknown** [comment]
Hm, something went wrong, but now it should be pushed^^

https://github.com/misterunknown/ifm/commit/a625b15598c130bd6eafb7664df7536a665e88ab

**Comment by stenioaraujo** [comment]
Just tested, it works great. Thank you.
