### ISSUE TITLE
Feature Request: Share or Copy external link

### ISSUE THREAD

**Issue by Licen-it** [misterunknown/ifm#117]
Is it possible to have a share option or something in the config to have the copy link option actually copy the real url to the file instead of the proxy one?

**Comment by misterunknown** [comment]
Did you set a custom root_dir? In this case IFM assumes that this directory is not publicy accessible, and therefore copies the proxy link. Unfortunately there is no other way to safely determine if the root_dir is accessible via the webserver.

**Comment by Licen-it** [comment]
Yes that option is set...my structure is like this:
```
IFM folder
|---ifm.php
|---files folder
|---temp dir
```
I was hoping for a new configuration flag to explicitly specify if the root dir is public

**Comment by misterunknown** [comment]
Sorry for the late reply, I was some days off. I have to think a bit about it, but I guess it shouldn't be a problem. I just want figure out the best solution.

**Comment by misterunknown** [comment]
You can now set `root_public_url` in order to specify a public URL for the root_dir. I'll add that to the documentation soon.
