### ISSUE TITLE
Request: Make the back button work and have folder URLs

### ISSUE THREAD

**Issue by Jwink3101** [misterunknown/ifm#12]
First of all, let me say that I don't want to sound ungrateful for the work you've done and shared. I am using it (though *any* web file manager is not my main interface to my files) and it has been great.

But anyway, it would be great if there was a change to the URL on navigating folders, etc. This way, I may (a) directly link back and (b) have a responsive back button that behaves has one would expect.

For example, see [simple-file-manager](https://github.com/jcampbell1/simple-file-manager)

Thanks!

**Comment by misterunknown** [comment]
Thanks for your feedback! I'll add this to my todo list.
