### ISSUE TITLE
Docker Default Timezone

### ISSUE THREAD

**Issue by Dodgexander** [misterunknown/ifm#120]
Hey just wondering if there's a way to set the docker IFM_DEFAULTTIMEZONE variable?

I set to IFM_DEFAULTTIMEZONE=1 and its Berlin, set to 2 and still Berlin.

Tried the PHP code to change it to IFM_DEFAULTTIMEZONE=America/Detroit but no hope!

thanks for your great work!

**Comment by misterunknown** [comment]
Yes, obviously this is hard-coded in the Dockerfile. I'll fix that soon! :)

**Comment by misterunknown** [comment]
I fixed that issue. I noticed that `defaulttimezone` had no effect so far, so I renamed the config option to simply `timezone` respectively `IFM_TIMEZONE`.

I fixed the complete Dockerfile, so I hope I didn't break anything else :-P

**Comment by Dodgexander** [comment]
Please forgive me @misterunknown but what is the correct format? I have tried `IFM_TIMEZONE=America/Detroit` and `IFM_TIMEZONE="America/Detroit"` but its still picking out Berlin.

**Comment by misterunknown** [comment]
Hm, are you sure, you using the latest version? Please also run the following:
```
docker exec -ti ifm /bin/sh
echo $IFM_TIMEZONE
exit
```

**Comment by Dodgexander** [comment]
Hope this helps:

> bash-4.3# $IFM_TIMEZONE
> bash: "America/Detroit": No such file or directory

I should be on the latest version, each time to test I have been deleting the container and removing its volume.

Output of docker inspect:

> tim@basement:~/docker$ docker inspect ifm
[
    {
        "Id": "1ea5234689680470539e19561aa9a977398ea044fa85bac0fad6fa565b493ee6",
        "Created": "2020-01-14T22:56:54.960790469Z",
        "Path": "docker-startup.sh",
        "Args": [],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 32026,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2020-01-14T22:56:59.428143235Z",
            "FinishedAt": "0001-01-01T00:00:00Z"
        },
        "Image": "sha256:2643545607532df1c486f91eae468c1509799131bd8c7e5039131222d1cd5874",
        "ResolvConfPath": "/var/lib/docker/containers/1ea5234689680470539e19561aa9a977398ea0                                                                                                                                                                                                                                 44fa85bac0fad6fa565b493ee6/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/1ea5234689680470539e19561aa9a977398ea044                                                                                                                                                                                                                                 fa85bac0fad6fa565b493ee6/hostname",
        "HostsPath": "/var/lib/docker/containers/1ea5234689680470539e19561aa9a977398ea044fa8                                                                                                                                                                                                                                 5bac0fad6fa565b493ee6/hosts",
        "LogPath": "/var/lib/docker/containers/1ea5234689680470539e19561aa9a977398ea044fa85b                                                                                                                                                                                                                                 ac0fad6fa565b493ee6/1ea5234689680470539e19561aa9a977398ea044fa85bac0fad6fa565b493ee6-json.lo                                                                                                                                                                                                                                 g",
        "Name": "/ifm",
        "RestartCount": 0,
        "Driver": "overlay2",
        "Platform": "linux",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "docker-default",
        "ExecIDs": [
            "1aa75b42cd081948e7dcdd45db09ec5f8aea5cdee0c77a7b279dd059fc4713e6"
        ],
        "HostConfig": {
            "Binds": [
                "/mnt/data:/var/www/html/data:rw"
            ],
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "docker_default",
            "PortBindings": {
                "80/tcp": [
                    {
                        "HostIp": "",
                        "HostPort": "8990"
                    }
                ]
            },
            "RestartPolicy": {
                "Name": "unless-stopped",
                "MaximumRetryCount": 0
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": [],
            "CapAdd": null,
            "CapDrop": null,
            "Capabilities": null,
            "Dns": null,
            "DnsOptions": null,
            "DnsSearch": null,
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "shareable",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": null,
            "DeviceCgroupRules": null,
            "DeviceRequests": null,
            "KernelMemory": 0,
            "KernelMemoryTCP": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": null,
            "OomKillDisable": false,
            "PidsLimit": null,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0,
            "MaskedPaths": [
                "/proc/asound",
                "/proc/acpi",
                "/proc/kcore",
                "/proc/keys",
                "/proc/latency_stats",
                "/proc/timer_list",
                "/proc/timer_stats",
                "/proc/sched_debug",
                "/proc/scsi",
                "/sys/firmware"
            ],
            "ReadonlyPaths": [
                "/proc/bus",
                "/proc/fs",
                "/proc/irq",
                "/proc/sys",
                "/proc/sysrq-trigger"
            ]
        },
        "GraphDriver": {
            "Data": {
                "LowerDir": "/var/lib/docker/overlay2/0ea043e392daa874687b558193c52e46bbc07e                                                                                                                                                                                                                                 7046a028e28c609f454ba222d5-init/diff:/var/lib/docker/overlay2/3bca6ee236f068bd231b587fce4e41                                                                                                                                                                                                                                 121500e43269c6ff0b9d152d0b3985df11/diff:/var/lib/docker/overlay2/45ed129740235e6f030135150f1                                                                                                                                                                                                                                 3f1686de7a14f0e4179c7ba7155271b28a070/diff:/var/lib/docker/overlay2/a83e4679d0c322b1f2e4a5fa                                                                                                                                                                                                                                 8b24c019e3dfff8681a7349d5ab0c30e420bed39/diff:/var/lib/docker/overlay2/6e42649c9f91191ea0bd5                                                                                                                                                                                                                                 b13d67e8bbc2c8b07c55d1375b3d824b851901c2d54/diff:/var/lib/docker/overlay2/b87a251964d00ea21f                                                                                                                                                                                                                                 bfabdeeaeed364ca5725b965a5bfc738237fd5db9fda32/diff:/var/lib/docker/overlay2/4eb8dde00b3b6d5                                                                                                                                                                                                                                 da60987aa48856c5aa946a35151185519b489041835b60e8d/diff:/var/lib/docker/overlay2/d8404f654375                                                                                                                                                                                                                                 115746fcff95c57b4cdebce1b356a585e7a2b6e8a450e78620aa/diff:/var/lib/docker/overlay2/a6d6f5ef2                                                                                                                                                                                                                                 2ad1411dedae64e6d5a06a2193953b8a6fab6ac5d0750e91abb0d96/diff",
                "MergedDir": "/var/lib/docker/overlay2/0ea043e392daa874687b558193c52e46bbc07                                                                                                                                                                                                                                 e7046a028e28c609f454ba222d5/merged",
                "UpperDir": "/var/lib/docker/overlay2/0ea043e392daa874687b558193c52e46bbc07e                                                                                                                                                                                                                                 7046a028e28c609f454ba222d5/diff",
                "WorkDir": "/var/lib/docker/overlay2/0ea043e392daa874687b558193c52e46bbc07e7                                                                                                                                                                                                                                 046a028e28c609f454ba222d5/work"
            },
            "Name": "overlay2"
        },
        "Mounts": [
            {
                "Type": "bind",
                "Source": "/mnt/data",
                "Destination": "/var/www/html/data",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
        "Config": {
            "Hostname": "1ea523468968",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "80/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "IFM_AUTH=1",
                "IFM_API_CHMOD=1",
                "IFM_API_COPYMOVE=1",
                "IFM_API_CREATEDIR=1",
                "IFM_API_CREATEFILE=1",
                "IFM_API_EDIT=1",
                "IFM_API_DELETE=1",
                "IFM_API_DOWNLOAD=1",
                "IFM_API_EXTRACT=1",
                "IFM_API_UPLOAD=1",
                "IFM_API_REMOTEUPLOAD=1",
                "IFM_API_RENAME=1",
                "IFM_API_ZIPNLOAD=1",
                "IFM_GUI_SHOWLASTMODIFIED=1",
                "IFM_GUI_SHOWFILESIZE=1",
                "IFM_GUI_SHOWOWNER=1",
                "IFM_GUI_SHOWGROUP=1",
                "IFM_GUI_SHOWPERMISSIONS=1",
                "IFM_GUI_SHOWPATH=1",
                "IFM_GUI_CONTEXTMENU=1",
                "IFM_TIMEZONE=\"America/Detroit\"",
                "IFM_DOCKER_UID=33",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "PHP_INI_DIR=/etc/php5",
                "IFM_AUTH_SOURCE=inline;admin:$2y$10$0Bnm5L4wKFHRxJgNq.oZv.v7yXhkJZQvinJYR2p                                                                                                                                                                                                                                 6X1zPvzyDRUVRC",
                "IFM_ROOT_DIR=",
                "IFM_TMP_DIR=",
                "IFM_DEFAULTTIMEZONE=Europe/Berlin",
                "IFM_API_AJAXREQUEST=1",
                "IFM_GUI_SHOWHTDOCS=1",
                "IFM_GUI_SHOWHIDDENFILES=1"
            ],
            "Cmd": [
                "docker-startup.sh"
            ],
            "Image": "digitalmobil/ifm",
            "Volumes": {
                "/var/www/html/data": {}
            },
            "WorkingDir": "/var/www",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "com.docker.compose.config-hash": "1a615d565966a9b1c754a378264fce999fab17f72                                                                                                                                                                                                                                 0a325116dc399068597b973",
                "com.docker.compose.container-number": "1",
                "com.docker.compose.oneoff": "False",
                "com.docker.compose.project": "docker",
                "com.docker.compose.service": "ifm",
                "com.docker.compose.version": "1.23.2"
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "3f16e1aabba5fb35d0d78acc7422f53bf13e1db12418eb5568cc0d3c007a297e",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "80/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "8990"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/3f16e1aabba5",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "",
            "Gateway": "",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "",
            "IPPrefixLen": 0,
            "IPv6Gateway": "",
            "MacAddress": "",
            "Networks": {
                "docker_default": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": [
                        "1ea523468968",
                        "ifm"
                    ],
                    "NetworkID": "44fb8ef23a90f334b37604b053e2dd04c749a2b49203a3d6953e2be1df                                                                                                                                                                                                                                 16fc50",
                    "EndpointID": "07ad96312b3558c63fb32bb772df1b4777e9b62ef0ce5ce243114f672                                                                                                                                                                                                                                 0780f18",
                    "Gateway": "172.18.0.1",
                    "IPAddress": "172.18.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:12:00:02",
                    "DriverOpts": null
                }
            }
        }
    }
]

**Comment by misterunknown** [comment]
I guess this is the same problem as in #121. The `digitalmobil/ifm` docker container was a third party contribution. I merged that, but didn't ever use it myself. The new container image was build by me and is available as `pinknet/ifm:latest`.

**Comment by Dodgexander** [comment]
Okay (sorry for this).
I am using the correct version now and this time I get no timezone in ifm at all.

> /usr/local/share/webapps/ifm # echo $IFM_TIMEZONE
> America/Detroit

I also tried "America/Detroit" but it doesn't work.

>     ifm:
>         image: pinknet/ifm:latest
>         container_name: ifm
>         restart: unless-stopped
>         volumes:
>             - /mnt/data:/var/www/html/data
>         ports:
>             - '8990:80'
>         environment:
>             - IFM_AUTH=1
>             - IFM_API_CHMOD=1
>             - IFM_API_COPYMOVE=1
>             - IFM_API_CREATEDIR=1
>             - IFM_API_CREATEFILE=1
>             - IFM_API_EDIT=1
>             - IFM_API_DELETE=1
>             - IFM_API_DOWNLOAD=1
>             - IFM_API_EXTRACT=1
>             - IFM_API_UPLOAD=1
>             - IFM_API_REMOTEUPLOAD=1
>             - IFM_API_RENAME=1
>             - IFM_API_ZIPNLOAD=1
>             - IFM_GUI_SHOWLASTMODIFIED=1
>             - IFM_GUI_SHOWFILESIZE=1
>             - IFM_GUI_SHOWOWNER=1
>             - IFM_GUI_SHOWGROUP=1
>             - IFM_GUI_SHOWPERMISSIONS=1
>             - IFM_GUI_SHOWPATH=1
>             - IFM_GUI_CONTEXTMENU=1
>             - IFM_TIMEZONE=America/Detroit
>             - IFM_DOCKER_UID=33
>             - IFM_DOCKER_GID=33

**Comment by misterunknown** [comment]
> I am using the correct version now and this time I get no timezone in ifm at all.

What do you mean by "no timezone at all"? That's technically impossible, as there is a default fallback (afaik UTC). How do you exactly tell, which timezone is present?

**Comment by Dodgexander** [comment]
> > I am using the correct version now and this time I get no timezone in ifm at all.
> 
> What do you mean by "no timezone at all"? That's technically impossible, as there is a default fallback (afaik UTC). How do you exactly tell, which timezone is present?

Previously the timezone was displayed in the ifm webGUI but isn't any more. I think its set correctly though since I made a test file and the modified time in ifm was correct.

Thanks for all your help!

**Comment by misterunknown** [comment]
> Previously the timezone was displayed in the ifm webGUI but isn't any more

Ok, I didn't even know that, as I never display the modify times^^

> I think its set correctly though since I made a test file and the modified time in ifm was correct.

Ok, glad to hear. If you want the current timezone to be displayed, I could implement that.

**Comment by Dodgexander** [comment]
Its no biggie. All that matters really is seeing the correct file timelines
for modification :)
