### ISSUE TITLE
File Destination

### ISSUE THREAD

**Issue by marcbth** [misterunknown/ifm#123]
Hallo,

Glückwunsch zu der gelungenden Arbeit.

Hätte dennoch eine Frage:

Ist es möglich bei "File Destination"
die Punkte Copy Move Fix zu machen bzw. eine Scrollbar hinzuzufügen?

Bei einer längeren Ordnerliste ist es sehr umständlich immer zu scrollen.

Vielen Dank für die Mühe.

Möchte den Code in ompd (www.ompd.pl) integrieren. 

Cliff

**Comment by misterunknown** [comment]
> Ist es möglich bei "File Destination"
> die Punkte Copy Move Fix zu machen bzw. eine Scrollbar hinzuzufügen?
> 
> Bei einer längeren Ordnerliste ist es sehr umständlich immer zu scrollen.

Jo: c2002bc
