### ISSUE TITLE
Select Files

### ISSUE THREAD

**Issue by marcbth** [misterunknown/ifm#124]
Hallo,

wie kann ich mehrere Files bzw. Ordner auswählen? 
Hab das Beispiel gesehen und finde die Funktion einfach nicht.

würde am Anfang der Datei bzw. Ordner gerne einen hacken setzen und dann copy move delete auswählen können.

ich weiß ist viel.

Cliff

**Comment by misterunknown** [comment]
Du kannst mehrere Dateien/Ordner wählen, indem du <kdb>Strg</kdb> gedrückt hältst.

**Comment by marcbth** [comment]
Velen Dank für die schnelle Antwort.

Das Problem ist, ich habe einen MAC bzw. IPad.

Auswahl mit Leertaste funktioniert, aber wenn ich 2 Files auswähle kopiert er nur einen davon.

Für Tablets bzw. MAC wäre ein Hacken echt hilfreich.

Was mir noch aufgefallen ist bei der suche erscheint dann kein 'up' mehr. kann also nach der suche nicht mehr das directory ändern.

**Comment by marcbth** [comment]
Kopie mehrer Files funktioniert. War nur zu Verblendet und hab rechts auf copy gedrückt.

Mehrfachauswahl am IPad scheitert leider.

**Comment by marcbth** [comment]
Gibt es eigentlich eine möglichkeit, den ifm in eine andere seite (html bzw php) zu integrieren?

**Comment by misterunknown** [comment]
> Was mir noch aufgefallen ist bei der suche erscheint dann kein 'up' mehr. kann also nach der suche nicht mehr das directory ändern.

Das versteh ich nicht ganz.

> Mehrfachauswahl am IPad scheitert leider.

Das ist richtig, bisher hatte ich da keinen Bedarf. Ich kenn mich mit Touch-Events auch nicht so aus, aber ich guck mal nach.

> Gibt es eigentlich eine möglichkeit, den ifm in eine andere seite (html bzw php) zu integrieren?

Theoretisch ja, aber das hat noch keiner probiert^^ Du könntest es einfach probieren; einfach die libifm.php aus dem Build-Verzeichnis irgendwo verfügbar machen, und dann innerhalb deiner Applikation ungefähr folgendes ausführen:
```php
<?php
$ifm = new IFM();
if ($_REQUEST['api']) {
  $ifm->run("api");
  exit();
}
$foo->getInlineApplication();
?>
```
```javascript
<script>
var ifm = new IFM();
ifm.init("ifm");
</script>
```

**Comment by misterunknown** [comment]
Also das Problem ist komplizierter. Ich hatte damals keine Checkboxen eingebaut, weil man ja dann irgendein UI-Element braucht, welches anbietet, irgendwelche Aktionen auszuführen. Die Lösung war seinerzeit halt das Klicken mit Strg + Kontext-Menü.

Ich hab grade mal den Code des Kontext-Menüs angeschaut, den krieg ich nicht touchfähig gemacht, dazu hab ich zu wenig Ahnung. Gegen optionale Checkboxen hätte ich prinzipiell nichts einzuwenden, allerdings bleibt die Frage, wie man die Aktionen dann triggert.

Ich bin auch dabei, den IFM auf Bootstrap 4 umzustellen, dort sind Touch-Devices besser unterstützt. Allerdings liegt der Branch (#115) schon wieder recht lange rum, weil ich noch nicht dazu gekommen bin...

**Comment by marcbth** [comment]
schau mal bei
Checkbox

https://github.com/prasathmani/tinyfilemanager

vorbei. die machen das.

**Comment by marcbth** [comment]
> > Was mir noch aufgefallen ist bei der suche erscheint dann kein 'up' mehr. kann also nach der suche nicht mehr das directory ändern.
> 
> Das versteh ich nicht ganz.
> 
> > Mehrfachauswahl am IPad scheitert leider.
> 
> Das ist richtig, bisher hatte ich da keinen Bedarf. Ich kenn mich mit Touch-Events auch nicht so aus, aber ich guck mal nach.
> 
> > Gibt es eigentlich eine möglichkeit, den ifm in eine andere seite (html bzw php) zu integrieren?
> 
> Theoretisch ja, aber das hat noch keiner probiert^^ Du könntest es einfach probieren; einfach die libifm.php aus dem Build-Verzeichnis irgendwo verfügbar machen, und dann innerhalb deiner Applikation ungefähr folgendes ausführen:
> 
> ```
> <?php
> $ifm = new IFM();
> if ($_REQUEST['api']) {
>   $ifm->run("api");
>   exit();
> }
> $foo->getInlineApplication();
> ?>
> ```
> 
> ```js
> <script>
> var ifm = new IFM();
> ifm.init("ifm");
> </script>
> ```

dafür fehlt mir leider das fachwissen.

versuch gerade das in www.ompd.pl zu integrieren.

sprich neuer menupunkt und dann wird ifm aufgerufen. Standalone funktioniert das ganze richtig gut, problem ist die integration in die bestehende menüstrucktur, sprich header und footer von ompd und dein code dazwischen.

**Comment by marcbth** [comment]
gibt es eigentlich auch eine funktionierenden ifm als nicht onefile? im src verzeichnis sehe ich ja was du machst.

**Comment by marcbth** [comment]
"einfach die libifm.php aus dem Build-Verzeichnis irgendwo verfügbar machen"

hab es in meinen stammordner kopiert. lässt sich aber ncht ausführen ifm.php schon.

**Comment by marcbth** [comment]
Hab gerade gesehen, dass du schon gestern die Scollbar eingefügt hast. 

Klasse

Ging echt schnell. Vielen Dank.

**Comment by misterunknown** [comment]
> dafür fehlt mir leider das fachwissen.

Dann wirds eh schwierig den einzubinden. Es gibt da nicht die Möglichkeit das einfach zu "includen", einfach aufgrund der Architektur.

> gibt es eigentlich auch eine funktionierenden ifm als nicht onefile? im src verzeichnis sehe ich ja was du machst.

Nein. In der `src/main.php` wird nur die Klasse definiert, der Compiler führt dann erst alle Dateien zusammen, und schreibt den Code zur Initialisierung mit rein.

> hab es in meinen stammordner kopiert. lässt sich aber ncht ausführen ifm.php schon.

Das ist klar. Ist ja auch nur die "Klasse", ohne jegliche Initialisierung. Wie gesagt, erfodert die Einbindung des IFM in eine Applikation Kenntnisse in PHP und Javascript.

**Comment by marcbth** [comment]
Bin gerade dabei, denn onefile aufzulösen. Nicht einfach. Viel arbeit. Finde es lohnt sich aber. Ist ja ein tolles Programm. 

Hab mir den https://github.com/prasathmani/tinyfilemanager angesehen. Der hat checkboxen.
Mal sehen wie er das macht.


Danke für die schnelle Antwort.

Cliff

**Comment by misterunknown** [comment]
> Bin gerade dabei, den onefile aufzulösen. Nicht einfach. Viel arbeit. Finde es lohnt sich aber. Ist ja ein tolles Programm.

Im Endeffekt musst du nur die Includes anpassen (alles was mit `@@@` beginnt), und dann den Initialisierungs-Code aus dem Compiler mit reinkopieren.

> Hab mir den https://github.com/prasathmani/tinyfilemanager angesehen. Der hat checkboxen.
> Mal sehen wie er das macht.

Der hat ganz unten, unter der File-Liste ein paar Buttons mit denen man dann Aktionen triggern kann. Das ist aber IMHO nicht so geil, wenn man File-Listen mit >100 Dateien hat, denn dann muss man immer ganz runter scrollen, um irgendwas zu tun.

Für Touch-Events könnte ich mir vorstellen, dass das Kontextmenü aufgeht, wenn man lange gedrückt hält. Sowas hab ich aber noch nicht gemacht. Die aktuelle Bibliothek (bootstrap-menu) bietet das allerdings nicht.

Ich bin eigentlich grundsätzlich nicht ganz zufrieden mit Bootstrap, weil ich zu viele Plugins brauche (Kontext-Menü, Treeview, Notify), und eigentlich auch gern jQuery komplett elimieren würde, aber ich hab noch nichts besseres gefunden. Zumindest nichts, was vernünftig aussieht, und alles hat, was ich brauche.

**Comment by marcbth** [comment]
> Der hat ganz unten, unter der File-Liste ein paar Buttons mit denen man dann Aktionen triggern kann. Das ist aber IMHO nicht so geil, wenn man File-Listen mit >100 Dateien hat, denn dann muss man immer ganz runter scrollen, um irgendwas zu tun.

Die Buttons sind naja, ok. für mich eher interessant die Checkboxen vor jedem Ordner bzw Datei.
Das löst erstmal die allermeisten Probleme (kopieren von mehreren Dateien).

Für Touch events hab ich folgendes gefunden:
https://www.mediaevent.de/javascript/touch-events.html

**Comment by marcbth** [comment]
für treeview

https://www.bypeople.com/custom-checkbox-treeview-codepen/

**Comment by marcbth** [comment]
noch einen mit checkbox gefunden:

https://github.com/alexantr/filemanager


ach ja, ein freund von mir hat ein script geschrieben um ein project von git per html(php) upzudaten. Interesse?
Dann entfällt die git clone Geschichte etc.

**Comment by marcbth** [comment]
was mir aufgefallen ist und ich versteh es leider nicht:

wenn ich z.b.

in der rechten navbar

{{#config.createfile}}
						<li><a id="createFile"><span title="{{i18n.file_new}}" class="icon icon-doc-inv"></span> <span class="visible-xs">{{i18n.file_new}}</span></a></li>
						{{/config.createfile}}

entferne (brauch ich nicht)

dann muss ich am anfang immer einen refresh machen um die ordnerstruktur anzeigen zu lassen.

Wo hab ich denn meinen Denkfehler?

**Comment by marcbth** [comment]
hat sich erledigt!!! Zum Glück

nächstes Problem

hab im Ordner root /var/user/share/music/hdd

wobei hdd ein symbolischer Link ist noch einen symbolischen Link

 /var/user/share/music/hdd/USB. /verweis auf /media/usb0

Problem ist es, der Inhalt wird nicht angezeigt

Gibt es dafür eine Lösung?

**Comment by marcbth** [comment]
sobald ich 

"root_dir" => "/home/soulm/share/music/hdd/USB",

eintrage funktioniert es
