### ISSUE TITLE
Symbolische Links werden nicht erkannt

### ISSUE THREAD

**Issue by marcbth** [misterunknown/ifm#125]
Hallo,

hoffe ich nerve nicht. 

hab im Ordner root /var/user/share/music/hdd

wobei hdd ein symbolischer Link ist noch einen symbolischen Link

/var/user/share/music/hdd/USB. /verweis auf /media/usb0

Problem ist es, der Inhalt wird nicht angezeigt.

Das gleiche passiert, wenn ich

/var/user/share/music 

nehme und darin sind 2 symbolische links enthalten (hdd,usb) hdd und usb werden angezeigt, aber ich kann nicht in die Ordner 

sobald ich

"root_dir" => "/home/user/share/music/hdd/USB",

eintrage funktioniert es

Gibt es dafür eine Lösung?

Cliff

**Comment by misterunknown** [comment]
Das ist ein Sicherheitsfeature, was aktuell nicht abschaltbar ist. Der höchste "Level-of-Operation" ist das `root_dir`. Allen Symlinks, die auf Ziele außerhalb dieses `root_dir` zeigen, wird nicht gefolgt.

Wenn du das umgehen willst, kannst du theoretisch Bind-Mounts verwenden.

**Comment by marcbth** [comment]
danke für die Antwort.

leider ist es ein Feature! 

dein tip mit Bind-Mounts funktioniert wunderbar. musste aber deswegen samba ändern.
es wäre schön wenn du das mal ändern könntest ala 

// use absolute path of directory i.e: '/var/www/folder' or **$_SERVER['DOCUMENT_ROOT'].'/folder'**
$root_dir = $_SERVER['DOCUMENT_ROOT'];

**Comment by marcbth** [comment]
Was ich nicht mit Bind-Mount lösen konnte ist die Ordnerstruktur.

gewünscht:

hdd
usb

unter
/var/www/mount 

anstatt geht es wohl nur mit 

/var/www/mount/hdd/usb

**Comment by misterunknown** [comment]
> // use absolute path of directory i.e: '/var/www/folder' or **$_SERVER['DOCUMENT_ROOT'].'/folder'**
> $root_dir = $_SERVER['DOCUMENT_ROOT'];

Das kannst du ja schon jetzt innerhalb des Skripts so setzen. Generell ist das aber für die meisten User nicht sinnvoll: Die legen den IFM einfach irgendwo in einen Ordner und wollen ihn auch nur im Kontext dieses Ordners verwenden.

Sofern du auf die Updatefähigkeit anspielst: Du kannst den IFM ja auch über Umgebungsvariablen konfigurieren. Dann musst du nicht innerhalb des Skripts rumschreiben.

> Was ich nicht mit Bind-Mount lösen konnte ist die Ordnerstruktur.

Das verstehe ich nicht ganz. Wenn du beide Ordner innerhalb dessen Verfügbar machen willst kannst du das ja so tun:
```
mkdir /var/www/mount/{hdd,usb}
mount -o bind /pfad/zur/hdd /var/www/ifmroot/hdd
mount -o bind /media/usb0 /var/www/ifmroot/usb
```

**Comment by misterunknown** [comment]
Wenn Umgebungsvariablen sich für dich nicht eignen, kannst du auch ein Wrapper-Skript nutzen:
```php
<?php
require_once("pfad/zur/libifm.php");

$config = array(
    "root_dir" => "/var/www/mount",
    ...
);

$ifm = new IFM($config);
$ifm->run();
