### ISSUE TITLE
MP4 video file upload failed

### ISSUE THREAD

**Issue by nabilsayeed** [misterunknown/ifm#126]
I tried to upload mp4 video files but failed. Could you please resolve the issue? Also is it possible to play uploaded videos without downloading?

**Comment by misterunknown** [comment]
> I tried to upload mp4 video files but failed. Could you please resolve the issue?

If the upload fails, you likely have a problem with PHP itself. Check `upload_max_filesize` and `post_max_size`.

> Also is it possible to play uploaded videos without downloading?

Most browsers play the video instantly if you click on it.
