### ISSUE TITLE
zipnload

### ISSUE THREAD

**Issue by nabilsayeed** [misterunknown/ifm#127]
Hi,

If I disable zipnload, the download icon disappears. Also zipnload not working. Do I need any extra modules installed?

**Comment by misterunknown** [comment]
> If I disable zipnload, the download icon disappears.

Thanks for the hint, I fixed that in the latest commit.

> Also zipnload not working. Do I need any extra modules installed?

Please check the [requirements](https://github.com/misterunknown/ifm#requirements), especially `phar`, `zip` and `zlib`.

**Comment by nabilsayeed** [comment]
Thanks for the quick fix. Is it possible to add "Refresh" and "Search" option in config so that I can hide them as well

**Comment by bahnfrei** [comment]
you may want to check your web server log for errors, perhaps you run into the same issue [#131](https://github.com/misterunknown/ifm/issues/131#issue-615896182) i did?

**Comment by misterunknown** [comment]
> Is it possible to add "Refresh" and "Search" option in config so that I can hide them as well

Wasn't possible, is now, in 7cfff04. I also noticed a bug in the search results (it didn't change the directory when clicking on a result). If that was the reason you wanted to hide it, now it's gone.
