### ISSUE TITLE
Sorting does not work

### ISSUE THREAD

**Issue by nabilsayeed** [misterunknown/ifm#128]
Sorting filename does not work. See screenshot
![sorting](https://user-images.githubusercontent.com/63577066/79850151-d798b180-8406-11ea-97dc-9b00f2fb992f.png)

**Comment by misterunknown** [comment]
This is the intended order - a numeric sorting of filenames is not really sensible. You can just add preceding zeros to the single-digit filenames, then it sorts your files as you intended to:
```
01.JPG
02.JPG
...
10.JPG
...
```
