### ISSUE TITLE
IE11 Issue

### ISSUE THREAD

**Issue by nevanderson9999** [misterunknown/ifm#129]
Hi, great project, however it won't run on IE11, any suggestions ?

**Comment by misterunknown** [comment]
IE11 does not support arrow functions, which I use. Do you need to use IE11?

**Comment by nevanderson9999** [comment]
Hi Thankyou for your reply if it was my choice no I wouldn’t use ie11 but the organization we are using it in has a ie11 policy until they upgrade to edge but we have no time scale for this, I take it IFM won’t work with ie11 without major changes ??

Thanks for your time

Neil

**Comment by misterunknown** [comment]
> I take it IFM won’t work with ie11 without major changes ??

Well, the issue with the arrow functions should not be too hard to "fix", but I'd bet that there are some other issues too, which I'm not aware of. So yes, I'm not aiming for IE11 support at the moment.

Feel free to rewrite the arrow functions (just search for `=>` in the JS part) - if that's sufficient to run in IE11, I'll merge the changes. I myself are too busy at the moment, and the corona mess didn't help either...
