### ISSUE TITLE
directory upload

### ISSUE THREAD

**Issue by bahnfrei** [misterunknown/ifm#133]
Should it be possible to upload directories via drag & drop? Otherwise it would be a nice feature.

Currently there's just that error message:

```
General error occured: No or broken response.
```

**Comment by misterunknown** [comment]
No, at the moment this is not possible.

I did some tests: On the client side (browser) there are `webkitdirectory` and `directory` attributes for the HTML `input` element, but the directory structure gets lost on the server side, as you only have the filename for every file, and not the directory.

The only thing you can do at the moment is zipping the directory and extract it on the server. I may look at implementing a tiny webdav server, then you could at least use a client.
