### ISSUE TITLE
Feature Request: remember sorting order

### ISSUE THREAD

**Issue by cybermcm** [misterunknown/ifm#138]
Just coming from another file manager, I really like your script, it's working without any additional config from the beginning!
I'm missing one feature though: I'm used to have my files sorted by mod date which is possible but not remembered and even changed back to default on every action.
Since I'm mostly interested in the newest file I always have to click on 'last modified'.
Is there a way to remember 'my' view?

**Comment by misterunknown** [comment]
The filetable should now keep the state, including sorting. (68c36cd)

**Comment by cybermcm** [comment]
works perfectly, thank you!
