### ISSUE TITLE
Suggestion: Acknowledgement for duplicate file upload

### ISSUE THREAD

**Issue by jojoschmitt** [misterunknown/ifm#141]
When uploading a file to a directory that already contains a file with the same name, the original file is simply replaced by the new uploaded file without a users consent.
This replacement could be unintentional and lead to data loss.
Would be really nice to notify the user in this case that a duplicate file name exists and offer some options.

Options could be: Replace, [Rename (uploaded file)], Cancel

Thanks!

**Comment by misterunknown** [comment]
Well, I added a hint if files are about to be overwritten, and give the choice of uploading anyway or cancel the upload. Giving the opportunity to rename each collision would be quite a bit of work, but feel free to implement it :)

**Comment by misterunknown** [comment]
Anyway, please let me know, if you guys notice any bugs, since I fixed some stuff along the way, and want to create a new bugfix release this week, as some features were broken (e.g. the context menu).
