### ISSUE TITLE
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fontello.svg, line 0)

### ISSUE THREAD

**Issue by maggie0002** [misterunknown/ifm#144]
When loading IFM after compiling locally the following error appears when viewing the page source in the browser:

`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (fontello.svg, line 0)`

It is point to:
http://hostname.local/font/fontello.svg?80353264

and returning 404 as it isn't present. 

Appears to all be working ok, but curious to the cause of the error. Any ideas?

**Comment by misterunknown** [comment]
Do you see any icons? If yes, then you can ignore this warning, I'll remove it with the next release.

If you build locally anyway, you can remove the font-face definition in `src/includes/fontello`, which does reference a font file by an `url`. Just remove the first 8 lines of `src/includes/fontello-embedded.css`. This should remove this error.

**Comment by maggie0002** [comment]
Seems to have done the trick. 

Seeing the same for: 

`[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (bootstrap.min.js.map, line 0)`

Is this also a quick fix?

**Comment by maggie0002** [comment]
Perfect, that did the trick. Thanks for the help, really appreciate your work developing this project, it's a game changer.
