### ISSUE TITLE
Remote Upload - cURL vs file

### ISSUE THREAD

**Issue by maggie0002** [misterunknown/ifm#147]
I assume cURL uses curl to retrieve the requested URL, but what does 'file' use and what are the pros/cons of each?

**Comment by misterunknown** [comment]
Yes, curl ueses curl, and file uses `file_get_contents`. I'm not really sure why I implemented these two methods, but I guess that I used the IFM on some servers, which didn't have the curl extension enabled. Maybe there were also some problems with following redirects from share-hosters. I guess nowadays curl would be sufficient, but I don't really know if anyone uses the file method.

**Comment by maggie0002** [comment]
Thanks for the info. 

I run everything on a VPS so have the ability to install curl on the host, or in any containers. Perhaps if someone doesn't I could see file_get_contents being useful, one less dependency? 

Wondering if there could be an option to enable or disable each of them through the api controls? I'm aiming for as simple and easy to understand interface for my project, which would mean hiding those options.

**Comment by misterunknown** [comment]
Well, I thought a bit about it, but don't really want to remove either of these options. If you want to simplify your interface, I guess one way would be to edit the template of the remote upload modal as such:
```diff
diff --git a/src/templates/modal.remoteupload.html b/src/templates/modal.remoteupload.html
index 62cce7f..0ed4ca8 100644
--- a/src/templates/modal.remoteupload.html
+++ b/src/templates/modal.remoteupload.html
@@ -9,17 +9,7 @@
                        <label for="filename">{{i18n.filename}}</label>
                        <input class="form-control" type="text" id="filename" name="filename" required>
                </div>
-               <div class="form-group">
-                       <legend>{{i18n.method}}</legend>
-                       <div class="form-check form-check-inline">
-                               <input class="form-check-input" type="radio" id="radiocurl" name="method" value="curl" checked="checked">
-                               <label class="form-check-label" for="radiocurl">cURL</label>
-                       </div>
-                       <div class="form-check form-check-inline">
-                               <input class="form-check-input" type="radio" id="radiofile" name="method" value="file">
-                               <label class="form-check-label" for="radiofile">file</label>
-                       </div>
-               </div>
+               <input type="hidden" name="method" value="curl">
        </fieldset>
 </div>
 <div class="modal-footer">
```

**Comment by maggie0002** [comment]
Thanks again for such a helpful response. I have incorporated this in and works great, thanks.

**Comment by misterunknown** [comment]
No problem 😃
