### ISSUE TITLE
Double menus on small screen

### ISSUE THREAD

**Issue by maggie0002** [misterunknown/ifm#151]
When using small window sizes, the menu at the top right has another menu within it that requires another click to expand it. This is particularly common on phones where the screen size is small.

Issue can be replicated by looking at the demo and making your browser window smaller. 

I hope all these requests are seen as constructive, I wish I had more coding abilities to be contributing more of these changes myself. They are certainly immensely helpful to me, and appreciate the work.

<img width="675" alt="Screenshot 2020-09-29 at 19 40 26" src="https://user-images.githubusercontent.com/64841595/94601743-d4de9a00-028b-11eb-9f36-2b44605dae93.png">

**Comment by misterunknown** [comment]
> When using small window sizes, the menu at the top right has another menu within it that requires another click to expand it. This is particularly common on phones where the screen size is small.

Fixed this in the last commit.

> I hope all these requests are seen as constructive, I wish I had more coding abilities to be contributing more of these changes myself. They are certainly immensely helpful to me, and appreciate the work.

Yeah, no problem :) I don't have as much time for this project as I'd like to, so sometimes I respond a bit late, but I certainly appreciate all issues and bug reports and contributions. They are making this thing better, and that's the goal.

**Comment by maggie0002** [comment]
I went through pretty thoroughly trying out all the different features, so hopefully all quiet from me for a while (famous last words). I will have another click around after #143  is merged if helpful, but as things stand it seems like this is a really solid piece of work and I'm sure useful to many.

**Comment by misterunknown** [comment]
Yeah, I hope to get some time to work on #143 which is not only a big step towards a better coding style, but should also switch technically from custom hand-crafted errors and responses to senseful exception handling. I hope to get it working in the next few weeks.
