### ISSUE TITLE
Nothing displayed if "auth" => 1

### ISSUE THREAD

**Issue by j75** [misterunknown/ifm#154]
I have nothing displayed (white page) if I set `"auth" => 1`.
However I noticed that my browser's console displays some errors:
```
Uncaught TypeError: Invalid template! Template should be a "string" but "undefined" was given as the first argument for mustache#rende
r(template, view, partials)
    render https//myserver/.../IFM/:876
    initApplication https//myserver/.../IFM/:2716
    success https//myserver/.../IFM/:2707
    c https//myserver/.../IFM/:460
    fireWith https//myserver/.../IFM/:460
    l https//myserver/.../IFM/:460
    o https//myserver/.../IFM/:460
    send https//myserver/.../IFM/:460
    ajax https//myserver/.../IFM/:460
    initLoadI18N https//myserver/.../IFM/:2697
    success https//myserver/.../IFM/:2687
    c https//myserver/.../IFM/:460
    fireWith https//myserver/.../IFM/:460
    l https//myserver/.../IFM/:460
    o https//myserver/.../IFM/:460
    send https//myserver/.../IFM/:460
    ajax https//myserver/.../IFM/:460
    initLoadTemplates https//myserver/.../IFM/:2677
    success https//myserver/.../IFM/:2667
    c https//myserver/.../IFM/:460
    fireWith https//myserver/.../IFM/:460
    l https//myserver/.../IFM/:460
    o https//myserver/.../IFM/:460
    send https//myserver/.../IFM/:460
    ajax https//myserver/.../IFM/:460
    initLoadConfig https//myserver/.../IFM/:2649
    init https//myserver/.../IFM/:2864
    <anonymous> https//myserver/.../IFM/:2868
IFM:876:9023
    render https//myserver/.../IFM/:876
    initApplication https//myserver/.../IFM/:2716
    success https//myserver/.../IFM/:2707
    c https//myserver/.../IFM/:460
    fireWith https//myserver/.../IFM/:460
    l https//myserver/.../IFM/:460
    o https//myserver/.../IFM/:460
    (Async: EventHandlerNonNull)
    send https//myserver/.../IFM/:460
    ajax https//myserver/.../IFM/:460
    initLoadI18N https//myserver/.../IFM/:2697
    success https//myserver/.../IFM/:2687
    c https//myserver/.../IFM/:460
    fireWith https//myserver/.../IFM/:460
    l https//myserver/.../IFM/:460
    o https//myserver/.../IFM/:460
    (Async: EventHandlerNonNull)
    send https//myserver/.../IFM/:460
    ajax https//myserver/.../IFM/:460
    initLoadTemplates https//myserver/.../IFM/:2677
    success https//myserver/.../IFM/:2667
    c https//myserver/.../IFM/:460
    fireWith https//myserver/.../IFM/:460
    l https//myserver/.../IFM/:460
    o https//myserver/.../IFM/:460
    (Async: EventHandlerNonNull)
    send https//myserver/.../IFM/:460
    ajax https//myserver/.../IFM/:460
    initLoadConfig https//myserver/.../IFM/:2649
    init https//myserver/.../IFM/:2864
    <anonymous> https//myserver/.../IFM/:2868
```
Could this error be triggered by some unusual header or header value?

**Comment by misterunknown** [comment]
Which version of the IFM do you use? The precompiled version, or do you compile it yourself?

**Comment by misterunknown** [comment]
> Could this error be triggered by some unusual header or header value?

I guess not. The initialization process of the IFM follows four steps:
* load configuration
* load templates
* load i18n (translations)
* client-side application initialization

The first three steps trigger ajax requests which expect valid JSON answers. Additional headers in the HTTP response should be ignored.

You should be able to test this by opening the browser console and enter
```
ifm.config
```
This should display the configuration array.

**Comment by j75** [comment]
> Which version of the IFM do you use? The precompiled version, or do you compile it yourself?

The compiled one (from this site).

**Comment by misterunknown** [comment]
> The compiled one (from this site).

Hm, weird. Which file exactly do you use? I just tested `ifm.php` and set `auth => 1` and it works.

> BTW how could I compile it? (I haven't seen information, or I didn't look at the right place).

You can compile the IFM this way:
```
$ git clone https://github.com/misterunknown/ifm
$ cd ifm
$ php ./compiler.php --lang=en
```
Afterwards you find the results in the `dist` folder.

**Comment by j75** [comment]
> Which file exactly do you use?
ifm.php

But only this one! from a previous message, should I understand that I need other folders too? (templates, i18n,..)

To crypt the password I used
```
htpasswd -n -B admin
```

**Comment by misterunknown** [comment]
No, you only need this single file, and the password generation looks also good.

Can you force reloading the page while having the networking tab in the browser console open? You should see some XHR requests containing JSON objects. Could you validate these objects?

**Comment by misterunknown** [comment]
Another method you could use: Just open a browser and go to:
```
view-source:https://<your_domain_and_path>/ifm.php?api=getTemplates
```
For example:
```
view-source:https://ifmdemo.gitea.de/ifm.php?api=getTemplates
```
The copy the content and check, if this is a valid JSON file (e.g. [here](https://jsonlint.com/)).

**Comment by j75** [comment]
The XHR POSTs are valid JSONs, containing only
```
{"status":"ERROR","message":"not authenticated"}
```

`view-source:` produced a HTML source code, not a JSON.

**Comment by j75** [comment]
I wonder if it doesn't come from my PHP version, which is *7.4.3* (although that does not explain why without authentication it works smoothly).

**Comment by misterunknown** [comment]
I have an "educated guess": Do you use an Basic Authentication with your web server additional to setting `auth => 1`? This may interfere in 2.6.2. Can you test a self-compiled version?

**Comment by misterunknown** [comment]
(BTW: PHP 7.4 should work fine, I tested everything on 7.4.11)

**Comment by j75** [comment]
1. if I test with a local compiled version, I get the same thing,
1. I don't use Basic Authentication here

However, adding some `error_log` in the code I noticed that
 * the return from `checkCredentials()` is 1, so there's no type error,
* there's no **HTTP_X_IFM_AUTH** variable defined and
 * `session_status()` returns **1**

**Comment by misterunknown** [comment]
Hi, sorry for the late reply.

The function `checkCredentials` should return a boolean value. `session_status` should return 2 (which is equal to `PHP_SESSION_ACTIVE`), if the session is active.

Could you test it with a private tab in your browser? If this IFM instance is public accessible, you can email me the URL and the credentials, maybe I can work out the problem.

**Comment by j75** [comment]
> you can email me the URL

What e-mail, please?

**Comment by j75** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

Hi!

I hope this is the good e-mail...

The URL is: <https://server.famion.eu/ifm/ifm.php>
In the same folder there's also a file named ifm-0auth.php
(this you can access it with https://server.famion.eu/ifm/ifm-0auth.php
) where "auth => 0"

Best regards,

M. Ion
-----BEGIN PGP SIGNATURE-----

iQIzBAEBCgAdFiEE72k+9pjzrjNq9aR+jr+e14AjXokFAl+Ir+cACgkQjr+e14Aj
Xokjlw//ZUPPBAWsOJateQI8QKijCw9kQpiP0mrgtvZySByr72exSlZSlD3GP87U
tKH+Di2O7T2OB0LZDFDSzT2+D+DceOZhRgVr5edE40kPxneVTrgmzW0xKQ/p80gK
izbmt7cQeH/KmqjOgNQjVEaZyD/S42OSom6e1zYipfm09U8cC9H3331VUXAEVRX2
7v5fKm0h8tk0Ncbmv+VMb1Or3zbTo+YxHrzyIkxIU0q18KkynpRvKB/YbieLNKfC
CGw8NgjL1gshFHy7oWyKa/Ld4lwpCXZkJMssbShPXMSjMsgXe/RDdZGrb+2AcocF
DBych6u3rI8mAPtst7GQfgtJ4AxJnJL6G4wySnKpFJsPzQuZNRV9aK//4E08AjDS
jbaB/ED7XzapJPAnEoIXA6/K1iFtwArj+lQ6b2gxgkwUA2nMC24EWfycZKFwA8Dh
PQ/yq2DpwQ5jDyWF37FZBW/Wm61L9NKlVUwkoxwAlsP/R1taupVIezZ4DdgqkqkI
GJucFjA7CmSDdX+EyKwyBtIps1+OxNIK5ZpPvViomtseRVBecZ1S2OLnDYabEm88
VGW6ZnbmRyWP254z3A68JtlxWPSIpWHkPUl5fJkhkQI9o1lnEorHd/wgW8Pm8lET
lfw6yNRSBdZDvedgxhyAjGM2y8ALbfWD/VK6gVh4wkSyYxKHKeM=
=+ds+
-----END PGP SIGNATURE-----

**Comment by misterunknown** [comment]
Thanks for your mail, I'll take a look at it on Monday.

**Comment by misterunknown** [comment]
Ok, I took a look, and I guess the problem is that your webserver sends a different `set-cookie` header with every request. This is really weird, since it contains the path `/myphp/`, which is not associated with the IFM.

Can you upload this little test script? It can be used to test if a session is persistent.
```php
<?php
session_start();

if (!isset($_SESSION['session_created_at']))
    $_SESSION['session_created_at'] = date('r');

echo "<pre>";
print_r($_SESSION);

if (isset($_REQUEST['logout']))
    session_destroy();
```
If you call this script multiple times in your browser, it should initially set the `session_created_at` field and echo the same timestamp in all subsequent requests. If that's not the case, then you likely have some webserver configuration you're not aware of.

**Comment by j75** [comment]
Yes, it creates a new session each time; I shall look into that to see why.

**Comment by j75** [comment]
Yes, that was the problem - you may close this issue now.

Thank you for your help!

**Comment by misterunknown** [comment]
Ok, glad you resolved it!
