### ISSUE TITLE
Some files cannot be edited

### ISSUE THREAD

**Issue by arteze** [misterunknown/ifm#160]
If I use the Remote Upload option, I cannot edit the uploaded file.

**Comment by arteze** [comment]
I already solved it, I saw another issue:

https://github.com/misterunknown/ifm/issues/99

The solution is to change the following in the php:

    "disable_mime_detection" => 0,

For this:

    "disable_mime_detection" => 1,

It would be nice if it can be configured from the browser.

**Comment by misterunknown** [comment]
What mime type was your file? I'd rather add some editable mime types than allowing the client to decide weather a file is editable.

**Comment by arteze** [comment]
It was a txt file... It was actually .com, because I downloaded it with Remote Upload, but I renamed it to txt... It's curl to x.com

**Comment by misterunknown** [comment]
Hm, weird. Could you upload this file to [the demo](ifmdemo.gitea.de)?

**Comment by arteze** [comment]
Demo does not have remote upload option.

**Comment by arteze** [comment]
I already uploaded it by drag and drop.

https://ifmdemo.gitea.de/x.com

**Comment by misterunknown** [comment]
Thank you!

Weird, PHP thinks its mime type is "application/octet-stream", even if it contains only a single character. Maybe I should revise how the editability is defined, I had many corner cases where the PHP mime type detection is somehow wrong.

**Comment by arteze** [comment]
One solution I can think of is if it is an octet stream, detect if the first kb have no strange characters, in that case it could be edited as text.
