### ISSUE TITLE
RemoteUpload & AjaxRequest

### ISSUE THREAD

**Issue by novashdima** [misterunknown/ifm#164]
When opening this menus currenDir empty, so IFM change directory to root location.
So if I upload file throught this menus this files uploaded in root instead of current dir.

**Comment by misterunknown** [comment]
Confirmed, seems to be an error in the template. These links shouldn't have a href attribute. I'll fix that when I merged your pull request.

**Comment by misterunknown** [comment]
Is fixed in #164
