### ISSUE TITLE
Feature request: custom colours

### ISSUE THREAD

**Issue by maggie0002** [misterunknown/ifm#165]
I imagine there would be demand for being able to customise the colours of IFM (certainly would be helpful for me). Namely, the header, and the font/icon colours that are currently blue. With even more buttons being added in (https://github.com/misterunknown/ifm/pull/161), adding in more blue to the interface, this is on my mind more than before. 

Wondering if it would be possible to set # colours for these two through a variable in the 'gui controls' of the main config?

**Comment by misterunknown** [comment]
Hm, the interface is simply bootstrap, so you could [build your custom colored bootstrap](https://getbootstrap.com/docs/4.1/getting-started/theming/) and include it. I think this is the most clean way of doing it. You could also try to hassle with custom css which overrides the bootstrap colors.

**Comment by maggie0002** [comment]
For anyone finding this when searching for the feature, either building with custom coloured boostrap as suggested above, or this is the CSS to override. Place it at the bottom of style.css

                .bg-dark{background-color:#8F3A84!important} 
                a:link {color:#1F2937;}    /* normal link */
                a:visited {color:#1F2937;} /* visited link */
                a:hover {color:#1F2937;}   /* mouse over link */
                a:active {color:#1F2937;}   /* selected link */
