### ISSUE TITLE
chdir(): No such file or directory (errno 2) in /app/public/files/index.php on line 5926"

### ISSUE THREAD

**Issue by maggie0002** [misterunknown/ifm#174]
When using the download icon to download a file, the following message appears in my log:

`2021/07/26 21:30:46 [error] 103#103: *470 FastCGI sent in stderr: "PHP message: PHP Warning:  chdir(): No such file or directory (errno 2) in /app/public/files/index.php on line 5926" while reading response header from upstream, client: 172.18.0.1, server: _, request: "GET /upload-files/?api=download&dir=fileshare/test%205&filename=moodle_logo_small.svg HTTP/1.1", upstream: "fastcgi://127.0.0.1:8000", host: "0.0.0.0:8081", referrer: "http://0.0.0.0:8081/upload-files/"`

It is accompanied by a message in the console:

`[Error] Failed to load resource: Frame load interrupted (upload-files, line 0)`

I can reproduce the console error in the IFM demo (https://ifmdemo.gitea.de) by clicking the download icon on any file so presuming the log contains the same message too:

`[Error] Failed to load resource: Frame load interrupted (ifmdemo.gitea.de, line 0)`

**IFM 2.6.3**

**Comment by misterunknown** [comment]
Hm, I can't reproduce this, neither the php error, nor the console error. Is it still happening on ifmdemo.gitea.de for you?

**Comment by maggie0002** [comment]
I can't really remember anything about it, it was some time ago. Seems like it is still occurring (using Safari) but doesn't seem to impact the file being downloaded so probably isn't anything to worry about?
