### ISSUE TITLE
How to use a non-user owner:group to delete files in a folder

### ISSUE THREAD

**Issue by asparatu** [misterunknown/ifm#176]
I want to know if you are able to use a non-user and group account for example www-data:www-data?

**Comment by misterunknown** [comment]
I don't understand your question. What exactly is a non-user?

In general, the IFM runs as either the webserver user (www-data) or, if you use php-fpm, the defined pool user. Whether this user can delete or edit specific files is completely determined by the OS.

**Comment by asparatu** [comment]
@misterunknown what I mean is a system-only user that has no password. But I found a way to do it, I added my user to the www-data group and I was able to make changes to it.

**Comment by misterunknown** [comment]
OK, nice.
