### ISSUE TITLE
Discussion: Current state

### ISSUE THREAD

**Issue by misterunknown** [misterunknown/ifm#178]
Hi @maggie0002 and @novashdima,

first of all: I really want to apologize for my extremely long absence. The last two years brought some important changes for me, so I had no time at all for this project, even forgot about it, until now. I hope you are doing well!

Besides this, I'm quite astounded and amazed that you still worked on improvements. Being away for so long caused me to loose the overview over the current state of the code. Can I safely merge v4.0? Are your pull-requests based on this version or the current master? Maybe you can give me a quick insight on how you see the situation.

Cheers,
Marco

**Comment by maggie0002** [comment]
Hey @misterunknown,

I'm afraid I have lost track of where the code base is at now too. I think (emphasis on think) that all the pull requests could be merged in to one (https://github.com/misterunknown/ifm/pull/166#issuecomment-889997340). Perhaps would be viable for a v4.0 beta release to get it all compiled together and out in to the world, let it get tested for a while and see if anything comes up?

**Comment by novashdima** [comment]
Hi.
@misterunknown, I'm glad you're okay.
Everything is fine, except for the war in the country...

I use v4.0 from my branch (i merge some changes from @maggie0002 and @cryol branchs) in production, everything is working.
But it would be nice to update all packages to last versions, move more strings to i18n and I think about implementation of api request logging.

**Comment by misterunknown** [comment]
FIrst of all, I hope you are ok @novashdima, I didn't know that you are in Ukraine. I pray the war ends soon, f*ck Putin.

----

Ok, I merged all your pull requests to v4.0 and will do a comprehensive test, and finally merge it into the master. Thanks for your contributions!
