### ISSUE TITLE
Corrupted picture files

### ISSUE THREAD

**Issue by modjibe** [misterunknown/ifm#186]
Hi !

I am using IFM on a Yunohost home server. 

I am using a Mac.

I have an issue when I upload a picture file with Firefox or Safari : the picture file is corrupted and I can't preview nor open it. When I download the file, it is corrupted. 

I have not the issue with Chrome. 

I have not the issue with other file types. 

Best 

JB

**Comment by modjibe** [comment]
Dear Marco

Thanks for your time ! I'll try to explain my problem more in details.

*On Firefox / Safari :*

I uploaded a simple jpeg file, no preview and not able to download it, so I
can't test the file.

[image: image.png]

*On Chrome : *

No problem

[image: image.png]

**Comment by misterunknown** [comment]
Hm, that sounds more like a browser problem. Can you download the corrupted file directly (not via IFM) and inspect it?
