### ISSUE TITLE
[up] arrow does not return to previous directory

### ISSUE THREAD

**Issue by sback49** [misterunknown/ifm#188]
It may be me, but the [up] arrow does not return to previous directory. Is somthing set wrong. All other functions meet or exceed my needs. I am running a few websites helping scout groups.

**Comment by misterunknown** [comment]
Hi, sorry for the late reply. The [up] entry only works if you are in a subdirectory. On the highest level this does nothing. If you want to be able to navigate to a higher level than the IFM itself, you have to set a `root_dir`. Does that help you?
