### ISSUE TITLE
Minor Feature Request: Word wrapping (option) in text ediitor

### ISSUE THREAD

**Issue by Jwink3101** [misterunknown/ifm#19]
Ok, this is minor and you've been super amazing about working on features so I figured I'd throw it out there.

It would be great if there was an option to soft wrap in the editor. Maybe at window width or maybe at some column width. Not sure how easy this kind of thing is to do.

Thanks again!

**Comment by misterunknown** [comment]
I added a simple checkbox to do this. I'll add a little editor menu later.
