### ISSUE TITLE
Enable logs

### ISSUE THREAD

**Issue by ffiesta** [misterunknown/ifm#193]
Hi,

I add ifm to sub-folder in root, and change root_dir to something like `../data/doc` but when it load i don't see any files created by the default web application, but i can create files on root_dir.

When open i receive error **General error: no or broken response.**

**Comment by misterunknown** [comment]
"General error: No or broken response" hints at a PHP error. Can you show me your PHP error log file?

**Comment by ffiesta** [comment]
I this is php error:

`[27-Feb-2024 13:00:05 Europe/Lisbon] PHP Notice:  Uninitialized string offset: 1 in /home/xxx/public_html/wiki/libraries/parsedown-1.8.0-beta-6/Parsedown.php on line 1493`

To you understand my error I setup https://github.com/Zavy86/WikiDocs on sub-folder on my primary website like this **domain.pt/wiki/ifm** and changed root-dir to `"root_dir" => "../datasets/documents",`. Then i need to use direct url to access ifm like `domain.pt/wiki/ifm/ifm.php` this open fine ... but i receive the error "General error: No or broken response" and i cant see my folders.

If i direct access to `domain.pt/wiki/ifm/` i receive 404 error from **wikidocs**

My domain is on cpanel hosting.

When i setup on my windows 10 > laragon, this setup works fine.

After search on web, I dentify multiple causes ( php version, permission, primary htaccess block this, or i need to call this from primary application.

![general error](https://github.com/misterunknown/ifm/assets/25620658/435d78f9-cfb8-436b-a1ab-c85dea61b2b0)

**Comment by misterunknown** [comment]
Your PHP error is no error, but a notice, which does not cause a broken response, and it's not even IFM related as far as I see. Unfortunately there could be many reasons why this would fail. Have you tried to set the `root_dir` absolute instead of relative?
Otherwise you can inspect the broken response by opening the developer tools and go through the requests. When you find the failed request, you can see the contents of the response by clicking "preview".

**Comment by ffiesta** [comment]
In roo-dir i find a error-log and after check with google, i need to trun on fileinfo extension.

Pease add check to php enabled extension.

**Comment by misterunknown** [comment]
The fileinfo extension is already mention as a requirement [here](https://github.com/misterunknown/ifm?tab=readme-ov-file#requirements). I may add a dedicated test in the script itself in the future.
