### ISSUE TITLE
Invalid argument supplied for foreach

### ISSUE THREAD

**Issue by stefanarsicdev** [misterunknown/ifm#194]
Hi, when i get your project to install on local with xampp so i can test it i get this error displayed in my browser.

#!/usr/bin/env php bool(false)
Warning: Invalid argument supplied for foreach() in C:\xampp\htdocs\ifm\compiler.php on line 38

**Comment by misterunknown** [comment]
You are not supposed to call compiler via the apache webserver. The compiler is only for building the tool. You can either download the compiled releases [here](https://github.com/misterunknown/ifm/releases) or you can build the IFM yourself using [this example](https://github.com/misterunknown/ifm/wiki/Contributing#example).
