### ISSUE TITLE
Change permissions does not work

### ISSUE THREAD

**Issue by geri777** [misterunknown/ifm#25]
I am using Chrome. When I change any permissions on files or folders they are not saved. There is no ajax request after changing the permission - and I could not find a "save" button.

**Comment by misterunknown** [comment]
The form can be submitted by pressing <kbd>Enter</kbd>. I already thought about a "save" button for this, but didn't find a nice place yet. Are you able to trigger the ajax request by hitting <kbd>enter</kbd>?

**Comment by geri777** [comment]
Thanks for the super-fast support. Yes, that works. You might add an jQuery .blur() event on the input field. Anyway, great work. Thank you so much!

**Comment by misterunknown** [comment]
Thanks for the hint, I'll add the blur-event in the next release! :)
