### ISSUE TITLE
unidentified index with sessions

### ISSUE THREAD

**Issue by magmal** [misterunknown/ifm#27]
Line 1760 and line 1772 should have isset($_SESSION['auth']) statements

**Comment by magmal** [comment]
should not be isset I think as this will allow anybody to log in

**Comment by misterunknown** [comment]
I'll take a look at it asap ;)

**Comment by misterunknown** [comment]
Now the authentication function checks wheather the index is set or not. Please let me know if this isn't sufficient in your mind.
