### ISSUE TITLE
The subdir can't open in time.

### ISSUE THREAD

**Issue by Amamatthew** [misterunknown/ifm#28]
When I click any of the subdir icons  in the page, I get a empty reply below. And the subdir can't open  subsequently. Any hints? Thank u. 
`{"realpath":""}`

**Comment by misterunknown** [comment]
Thanks for your feedback. How does your setup look like? Do you use the IFM on a webspace or do you administrate your webserver yourself? Does the PHP user have sufficient permissions for entering the directory?

**Comment by misterunknown** [comment]
Any updates?

**Comment by misterunknown** [comment]
I'll close this for now. If you have any further information, you can reopen this issue.
