### ISSUE TITLE
Change init directory of the file management

### ISSUE THREAD

**Issue by Amamatthew** [misterunknown/ifm#29]
If we can specify a folder as the init directory of the file management shows instead of the folder ifm.php located. Because sometimes we calls the ifm.php class file as a third party library  in the application system.

**Comment by misterunknown** [comment]
Thanks for your feedback! I already work on this feature, but didn't merge it yet. Please have a look on issue #26. You can see the regarding branch [here](https://github.com/misterunknown/ifm/tree/issue-26). Please join the discussion there :wink:

**Comment by misterunknown** [comment]
You mentioned, that you want to embed the IFM as a third party libarary. Can you give me some more information about this? I recently thought about restructuring the code, so one could embed it directly in another application without hassling with iframes.

**Comment by Amamatthew** [comment]
I capture a piece of code，don't know whether it is helpful. Please read below, thank u.
namespace app\admin\controller;

use think\Db;
use file\IFM;
use file\IFMZip;
use file\IFMConfig;
use think\Config;
use think\Request;
use think\Controller;

/**
 *  Filemanage Controller
 *
 */
class Filemanage extends Authentication
{

    public function actionIndex()
    {
		/*
		   start program
		 */
		$ifm = new IFM();
		$ifm->run();
	}

**Comment by misterunknown** [comment]
Ah ok. So you don't use an iframe, but start the ifm directly in your script. Thanks for the info :)
