### ISSUE TITLE
Building the script with Bootstrap 4.

### ISSUE THREAD

**Issue by chopraaa** [misterunknown/ifm#31]
Hi. First off, thanks for the lovely script. It's a great help. I'd like to know how I'd go around building the source into a single file. I want to upgrade the CSS to Bootstrap 4 but it keeps breaking the Javascript when I do it in the main file. (zip/delete/etc., don't work).

[![Screenshot](https://s15.postimg.org/e1saq6ydn/tf2.trade-.png)](https://postimg.org/image/oom3vm6iv/).
Most of it went missing and the elements have to be changed to adapt to BS4.

**Comment by misterunknown** [comment]
Hi! Thanks for your efforts. I could take a look at it, if you provide me your code. You can send it to me via email (marco@misterunknown.de) or you fork this project and apply your changes.

**Comment by misterunknown** [comment]
Just for reference: https://github.com/chopraaa/ifm/pull/1

**Comment by misterunknown** [comment]
I just tested your latest version and found some little issues:
* The "editor options" are shown directly below the "editor options" button. Probably there is a little flaw in the markup.
* In the mobile view the navbar looks a bit broken, because the menu button overlaps the IFM branding.
* I would prefer a dark navbar instead of a light one. This is more a matter of taste though. Maybe I should add the possibility to use different themes.
Let me know if you have any questions ;)

**Comment by chopraaa** [comment]
Sorry, I have't really gotten around to look at it. 

- Forgot to push an update to the repository, although I've fixed this IIRC.
- Fixed too.
- I suppose I could make it darker as I've nothing against colors. It's a simple alteration so I guess anyone should be able to do it from light <-> dark if need be.

I'll push an update as soon as possible.

**Comment by misterunknown** [comment]
No problem. I plan an update this week, where I separated the html markup from the js code. So it is way easier to style that. In addition to that, different themes will be possible.

Regarding the dark navbar: I thought about .navbar-inverse ;)

**Comment by misterunknown** [comment]
I just pushed my current work in a new branch: https://github.com/misterunknown/ifm/tree/js-templates

You can find the templates in the `src/templates` directory. `app.html` contains the main markup (everything with the <body>). Furthermore most of the modals are now templates. Let me know what you think! :wink:

**Comment by misterunknown** [comment]
Note: I use mustache as a template engine. See http://mustache.github.io/

**Comment by misterunknown** [comment]
Hey :) I just pulled your fork again and noticed that it would be quite a hard work to bring your changes into the current version of the IFM, as there were many changes in the last few days. So, I close this issue for now.

But don't hesitate to create a pull request if you still work on this. It should be far easier now, as I almost completely rely on mustache templates.
