### ISSUE TITLE
user management

### ISSUE THREAD

**Issue by joshp23** [misterunknown/ifm#32]
Please add user classes. such as admin/user/guest so that only trusted users can do things like set permissions, delete, etc...

**Comment by misterunknown** [comment]
Well, I'm not quite sure if that meets the common use case for this script. Can you explain a bit how you want to use the script and for what purpose?

**Comment by joshp23** [comment]
Sure, there's a few cases this makes sense for me.

The most common is a file server that I set up for the family. I want to be able to let the wife and kids explore it without having to worry about them accidentally deleting any of the media, or causing any other havoc (sharing of links inappropriately, uploading inappropriate data, and so on). I still need to be able to use with full privileges as well for remote access when I am away from a shell. I realize that I could install the script twice on the same server for this. It would be better to have one, IMO.

This similar situation mimics itself across the spectrum for me. Uploading things like newsletters and other shared data to a common server that I don't want all of the people in my org having write access to, but having the convenience of a web-link for review, is nice, especially if it isn't google. They can browse revisions, some team members can upload, and I can manage who can review, who can revise, and who can upload. 

I can go on. It's just  a nice feature to have when you are working with teams and shared data or projects. One step further away from google.

**Comment by misterunknown** [comment]
Well, I understand what you want, but I think this is a bit overkill for the script. One basic demands of the IFM is that it remains a single script solution with no external dependencies. While developing this, I often pondered if I should soften this policy (for example when somebody requested a simple login function #3 ), but didn't do it in the end. A user management would require a place to store the user information itself, as well as the permissions. Furthermore there would be additional security concerns that have to be addressed. The main purpose of the IFM is to be a simple file manager for admins, and not really a file-sharing tool, even less a collaborating tool for teams.

However, the next big step I'm working on, is the ability to easily embed the IFM to other web applications. This will take me a bit more time, but in the end a solution for your problem could be a separate web application which handles the user and permission management and then embeds the IFM with an appropriate configuration.

I hope you see my point. Thank you for your feedback, anyway! :smile:

**Comment by joshp23** [comment]
H'm... it seems that user:passwords could be kept in a simple `array( user, password, role);` without the need for external storage. 

I do see your point about external libraries, etc. I feel the same way about authentication scripts ;) I suppose it wouldn't be too time consuming to write a simple index.php that handles a basic authentication mechanism and embeds specific ifm configurations. This actually seems like a more flexible approach than defining static roles... I like granularity in authorization schemes anyway.

With the addition of #37   `tmp` folder configuration, one can easily set fs write permissions to restrict uploading to a limited folder/partition, so #35 is handled, thank you.

**Comment by joshp23** [comment]
It occurred to me to mention that, in addition to user classes, a configurable upload directory is a security enhancement. If an ifm link gets into the wrong hands and security gets bypassed due to brute force, or someone neglecting to change the default user:pass, having a single upload to worry about instead of an entire fs is useful, it can be isolated size limited. Of course, this is relative to certain specific use cases where trivial access to uploading and deleting files in the fs is turned off in the main script.

**Comment by misterunknown** [comment]
> H'm... it seems that user:passwords could be kept in a simple array( user, password, role); without the need for external storage.

Well, that is right. When I developed the login function I also thought about managing the user directly through the IFM, but this is almost impossible, because the script would have to overwrite itself while changing the regarding lines. I really tried to do that but ran into several problem, for example many times the resulting file contained weird syntax errors or encoding errors etc. So I decided to let the user himself change the user definition. It's not as fancy as it should be, but it works.

Thus it would be possible to extend the login function, so that the `auth_source` config option can contain an array of multiple users. However, a per-user configuration would be needed, which is not really what I expect the IFM to have.

> I do see your point about external libraries, etc. I feel the same way about authentication scripts ;) I suppose it wouldn't be too time consuming to write a simple index.php that handles a basic authentication mechanism and embeds specific ifm configurations. This actually seems like a more flexible approach than defining static roles... I like granularity in authorization schemes anyway.

This is exactly what I thought of. A separate script could store the user and permission information in a database or whatever, which is IMHO much more sane than storing these information in a PHP array directly in the script.

> It occurred to me to mention that, in addition to user classes, a configurable upload directory is a security enhancement.

That's right. I'll take a look at the code and figure out how much work it would be to do.

**Comment by joshp23** [comment]
> the script would have to overwrite itself while changing the regarding lines...

Good point, however only true _if_ one is, for instance, managing users via IFM itself, or some interface other than just manually editing a user file, which seems sane enough since the script is using hashed passwords and the data file can be stored in a secure location.

>a per-user configuration would be needed, etc...

Right. The manual editing solution only makes sense if considering a small number of users. Anything beyond a handful (the size of a small collaborative team, for instance) seems like overkill, IMO, and would surely require a more robust solution. 

So adding an option for something like
```
<?php
function newuser(){
    $result = false;
    if( isset( $_POST['submit_check'] ) && $_POST['submit_check'] !== null ) {
        $authfile = '/path/to/auth.txt'; // or pulling from const auth_source = 'file;etc...'
        $name = (isset($_POST['username']) ? $_POST['username'] : 'some_default_or_action');
        $pass = (isset($_POST['password']) ? $_POST['password'] : 'some_default_or_action');
        $hash = password_hash( $pass, PASSWORD_DEFAULT ); 
        $result = file_put_contents('$authfile, $name. : . $hash . PHP_EOL , FILE_APPEND | LOCK_EX);
    }
    return $result
}
?>
```
that could require  `const auth_source` to be `file` with an option for an admin user class with access to such a function if enabled is out of the question?

It seems simple enough. 

Thinking... If that is to much, perhaps a pre-IFM auth script, like you mentioned, could open a stock IFM on useradd() and configure it according to user classes, renaming it according to (a hashed) user name, so when user bob logs in after admin lou creates the account, bob.php (or some such) is loaded. If bob.php is not found, then login error occurs. No need for bulky mysql database. h'm...

**Comment by joshp23** [comment]
In any case, even with a separate auth script, which may be overkill for those requiring a simple solution to add, say, a single sub-admin or assistant to the script, so an array still seems like a good fall-back option for such limited cases. Thought?

**Comment by misterunknown** [comment]
First of all, thanks for sharing your thoughts!

Regarding file-based authentication: You are right, the current solution is a bit dirty. I think a htpasswd-like format should be accepted, including support for multiple users. Anyway, a separate permission configuration is not quite my objection.

Regarding the permission management: I think in cases where only two roles are relevant (admin, guest) it would be sufficient to install two instances of the IFM with different configurations.

When it comes to embedding the IFM to another app, my idea is as follows: The external app handles the user login and permission management and generates an IFMConfig class. After that, it initializes the IFM js app. I plan to make the IFM work within a div, so one can design the frame as he likes. The JS app subsequently communicates with the configured backend url.

Off topic: I just added an improved zip-extraction function and added the ability to copy/move files. I would appreciate if you could test it a bit. You can find the changes in this branch: https://github.com/misterunknown/ifm/tree/v2.4.0

**Comment by misterunknown** [comment]
A little update: I just started to prepare the IFM for embedding it in another application. It's not finished yet as I have to perform a few more tests, but it looks quite easier as I thought. The IFM class now contains a default configuration which can be overwritten by passing an array to the constuctor.

I think of it like this:
```php
require_once("ifm.php");

$custom_config = array(
  "root_dir" => "/some/path",
  "auth" => 1,
  "auth_source" => "..."
);
$ifm = new IFM( $custom_config );
$ifm->run();
```
The javascript part fetches the configuration from the backend, and will be able to run within a div:
```html
<div id="div_for_ifm"></div>

<script type="text/javascript">
  var ifm = new IFM({ api: "path/to/backend" });
  ifm.init( "div_for_ifm" );
</script>
```
I let you know when I'm ready – it shouldn't take me too long to get it done.

**Comment by misterunknown** [comment]
I just released v2.4.0. This release includes the ability to embed the IFM. I will write a little wiki article to show how to use it.

**Comment by misterunknown** [comment]
I finally wrote a quick'n'dirty example on how to wrap a user management around the IFM: https://github.com/misterunknown/ifm-manager
At the moment it doesn't even checks the passwords, but the approach becomes clear. Maybe I pursue this in the future, but for now I concentrate on some improvements of the IFM itself.

**Comment by joshp23** [comment]
been wrapped up in afk issues. I will check this out. 

thanks

**Comment by misterunknown** [comment]
I added the ability to configure the IFM via environment variables. Maybe that could be also interesing for you. Check out [this wiki page](https://github.com/misterunknown/ifm/wiki/Configuration).

I close this for now. Let me know if you need anything ;)
