### ISSUE TITLE
request: set tmp location

### ISSUE THREAD

**Issue by joshp23** [misterunknown/ifm#34]
for the zip function, currently a subdirectory is used as a tmp folder. It would be great if there was a way to over-ride this to make a subdirectory in a user defined global tmp directory instead.

**Comment by misterunknown** [comment]
You are definitely right. I'll add this soon!

**Comment by misterunknown** [comment]
I just added this config option. I ran a few tests and it worked. Please let me know if you find any flaws. If it works I merge this branch into the master.

You can test it by downloading the version from this branch: https://github.com/misterunknown/ifm/tree/issue-34

**Comment by joshp23** [comment]
cool, I'll be sure to let you know if I run into any bumps-in-the-road.
