### ISSUE TITLE
Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; archive has a deprecated constructor

### ISSUE THREAD

**Issue by BrunoDeBarros** [misterunknown/ifm#4]
For better compatibility with PHP 7. Just needs changing the `archive` and `zip_file` classes to have a `__construct()` instead of `archive()` and `zip_file()`. I would've done it and sent a PR but I am not sure if you keep the code in a multi-file format somewhere and it'd be useless to do so. Let me know if you want a PR against this ifm.php!

And, thank you for your work on this! 😄 IFM is the only not-broken-on-modern-php single-file file manager with decent editing capabilities, and it's all AJAX-y to boot! It's a blessing for when trying to provide support to people who don't have FTP access to give you and their web hosting's control panel is terrible.

**Comment by misterunknown** [comment]
Thank you for the hint, I'll fix that soon ;)

**Comment by misterunknown** [comment]
By the way, if you want, you can create a PR. At the moment I don't use a multi-file format. I currently refactor the code anyway, so the next version gets more maintainable ;)

**Comment by misterunknown** [comment]
I just need a few days more to release the new ifm, so stay tuned ;) Your issue will be solved then and it will contain also some other improvements.

**Comment by BrunoDeBarros** [comment]
Haha, awesome! :smile: Thanks for taking care of this so quickly!

**Comment by misterunknown** [comment]
Hey ;) I finally finished the recreation of the ifm. I splitted the code up in multiple files and also fixed your issue with the zip class. I tested this version but there may be some bugs left I didn't notice. Please tell me, if you find any errors or improvements.

**Comment by misterunknown** [comment]
I guess this can be closed.

**Comment by BrunoDeBarros** [comment]
This is awesome! It's all nicely organised and much better for any future improvements or changes. :smile: Thank you so much for doing this. :)
