### ISSUE TITLE
Add support for other archive file types

### ISSUE THREAD

**Issue by misterunknown** [misterunknown/ifm#44]
Suggested file types:
* tar
* tar.bz2
* tar.gz
* tar.xz

**Comment by tuschl-digitalmobil** [comment]
`tar.bz2` and `tar.xz` would complete the picture for the unix-world ;-)

**Comment by misterunknown** [comment]
Indeed. I'm working on that ;)

**Comment by misterunknown** [comment]
Hm, I didn't manage to extract an tar.xz file, because it threw a weird checksum error. But I guess tar.gz and tar.bz2 are the most common linux archive types, so I close this. Maybe I'll add tar.xz support later.
