### ISSUE TITLE
No valid working directory

### ISSUE THREAD

**Issue by Abdulmanan0315** [misterunknown/ifm#48]
Hi,
First of all thanks for your powerful script it has all the beautiful tools for using.But i am facing a little problem when i set root_dir to a a folder that is present in the script's directory ,it shows the files perfectly but i am not be able to delete,copy,move,rename etc. the files in that folder .it gives this error "Error: No valid working directory".i don't want to show my whole script to the users but only the files which are present in a folder in script's directory.

**Comment by misterunknown** [comment]
Hi,
thanks for your feedback. I could reproduce this error easily. I'll take a look at this soon!

**Comment by misterunknown** [comment]
I just pushed an update which should fix that. Please let me know if it still doesn't work for you.

Thanks again for your feedback. If you find any flaws, don't hesitate to create a new issue ;)

**Comment by Abdulmanan0315** [comment]
thanks it works now.
