### ISSUE TITLE
Provide a context menu

### ISSUE THREAD

**Issue by Abdulmanan0315** [misterunknown/ifm#49]
Hi,
Thanks for your lovely script.It will be a lot good if you add a new feature so that along with selecting multiple files with buttons (arrow up,arrow down) and using space to select ,it would be better that we can also select multiple files by pressing cntrl and selecting with mouse arrow .Plus,after selecting multiple files we can Right Click with mouse and a delete option should prompt something like this image:
![image](https://user-images.githubusercontent.com/20532497/28493206-ea1132ee-6f2b-11e7-9a5d-a4a40e9a1458.png)

**Comment by jrondorf** [comment]
Would be great to have multiple file upload also ;-)

**Comment by misterunknown** [comment]
You already can select multiple files by pressing <kbd>ctrl</kbd> and left mouse button. However, a little context menu should not be a problem.

@jrondorf At the moment you have to start an upload for every single file. These uploads are processed parallel. But I guess you mean the ability to upload entire directories by drag&drop. This, indeed, would be nice, but is not really related to this topic. Can you create a new issue for that?

**Comment by misterunknown** [comment]
The context menu is now available in #70. I'll merge this branch soon, but I have to perform some more tests. If you want to try this version just download the version from [this branch (js-rewrite)](https://github.com/misterunknown/ifm/tree/js-rewrite)

**Comment by misterunknown** [comment]
I just merged the changes to master, see #70 .
