### ISSUE TITLE
Disallow invalid characters for new filename and directories

### ISSUE THREAD

**Issue by jrondorf** [misterunknown/ifm#53]
When creating new files or directory, it is good that slashes already checked, like here:
https://github.com/misterunknown/ifm/blob/master/src/main.php#L368

Just one example, as this is tested all around the code.

I did a bit of a research, and found out that not all servers allow all kind of characters, e.g. all kind of unicode character should be prohibited to be uses.

This could be solved with following preg_match:
```
if (preg_match('/^[a-zA-Z0-9 ._-]*$/', $dn) !== 1) {
	echo json_encode( array( "status" => "ERROR", "message" => "Allowed characters in directory names: a-zA-Z0-9 ._-" ) );	
} 
```

The regex a-zA-Z0-9 ._- fits quite good I think, maybe this should be made configureable.

**Comment by misterunknown** [comment]
Well, this is not as easy as it looks. Linux, for example, allowes pretty much every character in a file/directory name except the slash and \0 (NULL). Windows, on the other hand, has a set of explicit forbidden filenames.

Your example regex ist quite restrictive, as it does not allow quite common characters like brackets. I think I'll just add some windows-specific restrictions to stay as compatible as possible.

**Comment by jrondorf** [comment]
That's fine. Maybe you could create a central place where to configure it (or a central filename/directory name check method), I am more than happy 😊.

**Comment by misterunknown** [comment]
I created a new branch which takes your changes into account:
* considers static OS restrictions on filenames for windows and others ([see](https://github.com/misterunknown/ifm/blob/issue-53/src/main.php#L971-L981))
* considers custom configurable character limitations ($forbiddenChars)

Please take a look. I tested these changes, but maybe I missed something. If you approve, I'll merge it.

**Comment by jrondorf** [comment]
Thanks, will perform a test tonight.

**Comment by jrondorf** [comment]
Preventing of default and custom limitations works so far.

This would consider to prevent any HTML characters, as they could break opening the files, see #54 
'\\', '/', ':', '*', '?', '"', '<', '>',

**Comment by misterunknown** [comment]
See #54 .
