### ISSUE TITLE
Font Icons instead of embedded Images?

### ISSUE THREAD

**Issue by Concept211** [misterunknown/ifm#6]
I would love to implement lightweight font icons to reduce the file size a bit more of the script (to hopefully be able to run it on GoDaddy) and also display sharp, vector-based icons. I know it's not possible to embed the actual font icons into a single script, but you are able to simply load an external CDN like the [Font Awesome](http://fontawesome.io/) library. I'm not a huge fan of FA, but it would provide a quick and easy external solution without having to embed anything. Plus, they're about to release v5 of their collection, so there should be plenty of new icons to work with. I know a lot of changes would be necessary due to all of the icons and buttons currently being made up of IMG elements, but I think it would benefit the script. 

What do you think?

**Comment by misterunknown** [comment]
Well, the huge file size of the script is indeed a problem. Unfortunately, loading an external font from a CDN is not an option for me, because sometimes I use the IFM in environments where I'm not connected to the internet, or sit behind a restrictive proxy.

At the moment I work on a new version. To lower the filesize I will strip out some infantile features like different editor themes and try to reduce the dependencies like JQueryUI. Maybe I will also replace the ace editor by a more lightweight one. In addition to that I will look for some nice SVG icons, which can replace the base64 encoded pngs.

Anyway, thanks for your input!

**Comment by Concept211** [comment]
Sounds great! Thanks for your hard work. If there's anything I can do to contribute, please let me know.

**Comment by misterunknown** [comment]
Little update:

I found a way to directly embed a font into the single ifm file. At the moment I design a new frontend using bootstrap and some nice icons from fontawesome. While diggin around searching for a sufficient icon set I found [this awesome site](http://fontello.com/), which allowes one to create a custom set of icons. I think the update is ready by the end of the week.

**Comment by Concept211** [comment]
Great news, thanks!

**Comment by Concept211** [comment]
**Side note:**
Remember I was having issues with GoDaddy where I couldn't upload the file because it was too large? Well, it turned out to be an issue with the old server that my account was running on. They just recently set me up on a newer Linux server due to some other issues that I was encountering and I just tested IFM today and it works perfectly! ;)

**Comment by misterunknown** [comment]
Thanks for the update! Nice to hear that it runs with GoDaddy servers.

I just pushed my new version with bootstrap and font icons. Take a look! :)

**Comment by Concept211** [comment]
It looks great and at half the size! Great job!

One thing I'm really missing though is the image preview on hover. I'm sure it's on your list but I just wanted to bring it up.

**Comment by misterunknown** [comment]
Thanks. I'm glad you like it. Only the font icons could be more sane. But I didn't find any better icons, yet.

The image preview, as well as the multiselect function, will be added soon :)

**Comment by misterunknown** [comment]
Image preview and multiselect will be added in the next release, so I close this issue for now ;)
