### ISSUE TITLE
General error occured: No or broken response

### ISSUE THREAD

**Issue by adityakhaire** [misterunknown/ifm#78]
General error occured: No or broken response
when change root_dir
PHP Warning:  chdir(): No such file or directory (errno 2) in /home/xxxxx/public_html/xx/x/ifm.php on line 3833

how to disable create error_log file / change error_log file path

**Comment by misterunknown** [comment]
Well, the IFM itself does not create a log file. It just turns on PHPs `error_reporting` and disables `display_errors`. If you want to disable the error logging you have to do it in your webserver or php configuration. Alternatively you can edit the script and set `error_reporting` to `0` (it's right at the start).

By the way: Why would you disable error reporting?

**Comment by misterunknown** [comment]
Uh, apparently the IFM indeed creates a log file, if you use a htpasswd file for authentication. I just removed this unneccessary logging and pushed it to master.

**Comment by adityakhaire** [comment]
disable error reporting DONE thnk 
sir

**Comment by adityakhaire** [comment]
HOW secure script

**Comment by misterunknown** [comment]
For authentication, please see [authentication](https://github.com/misterunknown/ifm/wiki/Authentication). You can either set `auth` directly in the script, or configure it via [environment variables](https://github.com/misterunknown/ifm/wiki/Configuration#environment-variables).

**Comment by misterunknown** [comment]
I guess this can be closed. Let me know if you have any problems.
