### ISSUE TITLE
Embedding the IFM in a custom application

### ISSUE THREAD

**Issue by adityakhaire** [misterunknown/ifm#79]
IFM Login
Login failed.

"auth" => 1,
		"auth_source" => 'inline;admin:$apr1$1QQLMQXM$d2pEYgh7aFai7aOpyvXm71',

**Comment by misterunknown** [comment]
At the moment the password hash for the inline user definition has to be generated by PHPs `password_hash` function, not the htpasswd utility. You can generate this hash as following:
```bash
echo "yourpassword" | php -R 'echo password_hash( file_get_contents( "php://input" ), PASSWORD_DEFAULT ).PHP_EOL;'
```
I will add the possibility to also use hashes in the htpasswd format, soon.

**Comment by adityakhaire** [comment]
wokring done thank for rply fst

**Comment by adityakhaire** [comment]
TRYING TO ADD <?php include 'menu.php'; ?> this line under menu tab but not working
i want to add extra menu

**Comment by misterunknown** [comment]
I'm not sure what you mean. What do you exactly want to add?

**Comment by adityakhaire** [comment]
TRYING TO ADD 
`<?php
	include 'menu.php';
?>`

 this line under menu tab but not working
i want to add extra menu

**Comment by misterunknown** [comment]
Ah, now I understand. Where exactly did you add the line?

Maybe it would be better to fork this repository, commit your changes, and I'll take a look and fix it.

**Comment by adityakhaire** [comment]
no working under NAV menu

**Comment by misterunknown** [comment]
I guess you inerted this line in the template, but this can not work. Everything client-related has to be done in javascript, because the IFM is a single-page application, which only communicates via AJAX requests with the backend. If you want to add own menu entries, you have to do these steps:
* add the menu entry in the template
* add a javascript handler for the menu entry
* if anything should be done on the server side, you have to add a PHP function and trigger it via AJAX request

**Comment by adityakhaire** [comment]
try hold on sir

**Comment by adityakhaire** [comment]
i want to customize your file manger with my admin panel

**Comment by misterunknown** [comment]
Well, theoretically this is possible, but not tested at all. So, maybe it works, maybe not. If you find any problems, please let me know. Here are some general hints:
* To embed the IFM in an existing application, you have to write a wrapper for the `libifm.php` from the `build` directory. The only difference between the `ifm.php` and `libifm.php` is that the ifm.php directly starts the IFM in standalone mode, which is not sufficient for your use case.
* You can set the permissions for an instance by passing an array which contains the relevant keys to the constructor. This should be done in the wrapper script. I'll show a little example at the end.
* The IFM has a function called `getInlineApplication()` which prints all relevant CSS and Javascripts. You have to initialize the javascript part yourself and need to pass the appropriate api url for it.

Here is a little schematic example, which is not intended for copy&paste, but can give a feeling for what I mean. First of all, this could be an example of the wrapper script:
```php
<?php
include( "libifm.php" );

// If your admin panel handles several users, it's possible to also assign different
// permissions. So you could for example read them from a database and create an
// array. If you don't pass an array to the IFM constructor, the default configuration
// is used.
$yourPermissions = array( "root_dir" => "/", "tmp_dir" => "/tmp" );

// Next, you have to initialize the IFM backend. If you don't have a custom config
// you don't have to pass an array at all.
$myIFM = new IFM( $yourPermissions );

// Finally the IFM should handle the API calls from the JS app:
$myIFM->run( "api" );
```
This wrapper script is more or less independent from your own application, but has to be accessible from the client.

An example for embedding the IFM to your application could be the following:
```php
<?php
// Even in your own application the "libifm.php" has to be included, to get all the
// CSS and JS stuff. 
include( "libifm.php" );

// You also have to create an instance of the IFM. At this point, no configuration is
// needed, because this instance will not be the API endpoint for the JS app.
$ifm = new IFM();

// At this point, nothing is printed yet. So the next step is to print the relevant CSS
// and JS stuff, which you can do by calling the function getInlineApplication.
$ifm->getInlineApplication();

// Now you have a div with the class "ifm", but the JS app is not initialized yet. It is
// very important to set the API URL to the wrapper script, otherwise the IFM client app
// will not work.
print '
  <script type="text/javascript">
    var ifm = new IFM( { api: "/path/to/wrapperscript.php" } );
    ifm.init( "ifm" );
  </script>
';
```
If your admin panel is available on github or anywhere else, you can send me the link, and I'll help you embed the IFM there.

**Comment by misterunknown** [comment]
I just edited the title of the issue, because the topic obviously changed ;)

**Comment by adityakhaire** [comment]
not on github 
it's download site scirpt im installing on my cpanel 
plz send me your hangout id or mail id

**Comment by misterunknown** [comment]
You can send me a mail to marco@misterunknown.de.

**Comment by misterunknown** [comment]
(Solved via email)
