### ISSUE TITLE
Editing files

### ISSUE THREAD

**Issue by jonaslt** [misterunknown/ifm#82]
I think it would be wise that if you make edits and click out of edit modal it asks you if you really want to quit, or save the changes first.
You can simply accidentally lose some input.

**Comment by jonaslt** [comment]
Also, possibility to sort files according to modification date would be nice.

**Comment by misterunknown** [comment]
Well, this save question when the modal is closed was implemented in an earlier version. Must have get lost in the rewrite process.

For sorting ability I think I can use something like bootstrap datatables.

**Comment by misterunknown** [comment]
1. To prevent loosing input when editing a file, the IFM now silently refuses to close the modal if the file was changed and the closing was not triggered by one of the corresponding buttons.

2. For sorting I implemented [datatables}(https://datatables.net/). I guess filtering could be helpful too, so I let it activated.

You can see the changes in this branch: https://github.com/misterunknown/ifm/tree/issue-82

After some testing I'll merge it into master.
