### ISSUE TITLE
Changed root_dir: file copy / move dialog isn't showing all folders

### ISSUE THREAD

**Issue by jrondorf** [misterunknown/ifm#86]
When using the root_dir option to choose a different root directory (like a sub dir of the original directory), the file copy / move dialog is only showing the current folder, not all folders.

**Comment by misterunknown** [comment]
Well, I just tested this myself, but everything works as expected. Maybe your PHP user has no access to the missing directories?

**Comment by misterunknown** [comment]
But I noticed another error: If the target directory is not writable, the IFM doesn't recognize it, but simply tries to copy the files and shows a success message.

**Comment by jrondorf** [comment]
No. When using IFM on the Directory above, all folders are visible. And the folders are created by the same user. Strange.

**Comment by misterunknown** [comment]
Ah, ok, I tested using '/' as the root_dir. I'll try to choose a directory below the scripts location and test again.

**Comment by misterunknown** [comment]
Ok. So I tested the IFM on my pages with several `root_dir`s below the scripts location, but didn't recognize any errors or missing folders in the copy/move dialog.

* Do you see any errors in the servers error log?
* Did you maybe restrict some functions (`disable_functions`)? The IFM currently uses `glob()` to determine the directories.
* Do you have weird characters in the directory names? I tested many combinations and characters, but it is totally possible that I missed something important.
* You can manually trigger the function `getFolders()` by doing an ajax request with the IFM itself. Just open the ajax dialog, leave the url field blank and use the following string in the data textbox: ```api=getFolders&dir=path/to/folder```. Please note that the path must be relative to the `root_dir` and you have to `urlencode` all special characters. The response should contain a JSON array with all subdirectories which are in the directory (this function is not recursive, to enable lazy loading).

**Comment by misterunknown** [comment]
Any updates on this issue?

**Comment by jrondorf** [comment]
No. Maybe it is 1and1 related.
