### ISSUE TITLE
Active content removed

### ISSUE THREAD

**Issue by Jwink3101** [misterunknown/ifm#87]
Maybe this is user error, but I recently decided I should update my IFM install to the latest. I put it on the server (with a symlink of `index.php-->ifm.php`) and tried to set it up.

Upon loading it, I got a long stream of nothing but:

>     Active content removed Active content removed Active content removed Active content removed Active content removed Active content removed Active content removed Active content removed Active content removed Active content removed

I thought that maybe it was my config so I restarted with a fresh file (nothing changed) and I still got that.

Any suggestions? Is this just user error?

The older version worked fine but I cannot tell you exactly which one that is (side note, It would be good to have  date/version in the code somewhere)

**Comment by misterunknown** [comment]
Hi,

well, this is a strange error. Do you see any messages in the browser console? I'd guess this is either a javascript or browser problem. Does this error occur in private mode of your browser? (Most browsers don't execute browser plugins in private mode, so this is a handy way to test a site without these.) Which OS do you use?

The miasing version number is indeed a problem I didn't solve yet. Maybe I add a function to the compiler which adds the current commit ID and the build date to make debugging easier.

**Comment by Jwink3101** [comment]
Ok, so this (as with many "bug" reports) *may* have been on my end.

I tried again at home and it worked fine. At work we have an https intercept and I was using my host's shared certificate. I **know** it used to work in the older version (again, not sure which). I will have to do some more playing but for now, it seems to be working fine. I will also use LetsEncrypt to get a correct cert.

Two other notes:

1. Using hashes as version *embedded* is not worth the effort. The problem is, now you modify the file with the hash and it is out of date! I personally like to include the date as my version when it is a script without major releases
2. (this is unrelated), you may want to consider giving the option of *not* using ACE. I use ACE on my own project (and it was a PITA to get working with POST) and it stinks on mobile.

But regardless, thanks for the awesome software!

**Comment by misterunknown** [comment]
> I tried again at home and it worked fine. At work we have an https intercept and I was using my host's shared certificate.

Ok, this could be the reason. Mostly HTTPS intercept comes with a security appliance which checks the content. Maybe they don't like my javascript. The last thing I added to the JS was the datatables plugin [(this one)](https://datatables.net/).

> Using hashes as version embedded is not worth the effort. The problem is, now you modify the file with the hash and it is out of date!

I don't mean the hash of the file, but the git commit id, on which the build is based on. But I have to think about that a bit ;)

> you may want to consider giving the option of not using ACE

This is no problem. I'll add this option.

**Comment by Jwink3101** [comment]
Yes, it seems to have to do with the intercept. I guess the question for you as the maintainer (and owner) of the code is whether or not this is worth trying to address. Obviously, **I** want to you make the changes so I can use this at work, but I do not feel any sort of entitlement. (and I would argue that my employer is the one who is messing me up, not you). But with that said, if there is a way to have both working, that would be *really* great. 

~~In the mean time, my workaround, since I am the only one using this anyway, is to allow non-https connection. I will be diligent to only connect on https when *not* at work and not worry about it when at work since the intercept means there really is no added security anyway!~~ (**nope**: even over http, it doesn't work).

Oh well. I guess I will have to find another solution when at work. Too bad too since IFM checks literally every other box I was looking for in a web-based file manager. I guess beggars can't be choosers.

(Maybe I will use your design and build myself a python backend to do it... I stink at the design side of things. I know python well but can just barely do minor things in JS. If I do this, I will of course credit the design to you and keep you updated...)

**Comment by misterunknown** [comment]
> Yes, it seems to have to do with the intercept. I guess the question for you as the maintainer (and owner) of the code is whether or not this is worth trying to address.

Well, I'd like to fix the problem, so you can continue using the IFM, but I don't really know how to do it. As you wrote, both HTTP and HTTPS are not working, so I am a bit clueless. Maybe you could test some of the [other releases](https://github.com/misterunknown/ifm/releases), so maybe I can guess which update introduced the problems. Perhaps it is also possible to ask your companies admin which website features are getting blocked or what the error message "Active content removed" actually means.

**Comment by Jwink3101** [comment]
I will later test older versions but I did just hear back from my IT department that this is related to a recent security change. I am working with them to see what I can do from their end.

Thanks!
