### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Jwink3101** [misterunknown/ifm#88]
It would be great to allow IFM to remember you for some amount of time. I think it works on cookies so if you set a longer expiration, it should work fine. Right?

Maybe make it an option in the config?

**Comment by misterunknown** [comment]
The IFM uses PHP sessions for authentication, so you can adjust session lifetimes by changing your PHP configuration. There are several relevant options, namely `session.gc_maxlifetime`, `session.gc_probability` and `session.gc_divisor`. For an explanation of how these options work, see [this answer on stackoverflow](https://stackoverflow.com/a/1270960) ([respectively the PHP reference](http://php.net/manual/en/session.configuration.php#ini.session.gc-probability)).

Apparently these configuration options can be set by a PHP script, but I don't really know if that is senseful. I'll do some tests and keep you updated.

**Comment by misterunknown** [comment]
I added the following options:
 * `session_lifetime` which defines the session lifetime in seconds
 * `force_session_lifetime` (boolean) which internally forces the garbage collector to check the session lifetime on every request
It's available in the latest commit, but I didn't set default values.
