### ISSUE TITLE
Owner and Group not available on Windows

### ISSUE THREAD

**Issue by Concept211** [misterunknown/ifm#9]
When running on a Windows server, the Owner and Group columns are not available. Server type should be checked and override the display owner and display group settings to automatically hide so that the table header and rows aren't mismatched.
![image](https://cloud.githubusercontent.com/assets/589002/20788973/c5f915f6-b780-11e6-8710-5cdbe9307df1.png)

**Comment by misterunknown** [comment]
I fixed it with the latest commit to master:
https://github.com/misterunknown/ifm/commit/7d9ee3fe6539c6c979585f311df2af660e1093f5
