### ISSUE TITLE
Remove Edit button on binary files

### ISSUE THREAD

**Issue by Tux12Fun** [misterunknown/ifm#90]
Hi,
first thank you very much for this great one file Expolorer. It's realy great.

I have only two whishes. 
1. hide the edit button on binary files (mp3 avi zip, rar)
2. Encoding of Textfiles. I noticed wrong Chars if I type the file in the Editor. (ö ü ß ...)

**Comment by misterunknown** [comment]
> hide the edit button on binary files (mp3 avi zip, rar)

Done.

> Encoding of Textfiles. I noticed wrong Chars if I type the file in the Editor. (ö ü ß ...)

Well, the IFM uses UTF-8 as the default. It can't be changed. Please provide some additional information:
* Which webserver do you use?
* Which PHP version do you use?
* Which browser(s) is/are affected?
* Can you reproduce this error with the [ifmdemo](https://ifmdemo.misterunknown.de)?

Thanks!

**Comment by misterunknown** [comment]
Any updates on this issue?
