### ISSUE TITLE
Drag n Drop not working

### ISSUE THREAD

**Issue by hexacubeindia** [misterunknown/ifm#91]
Uploading file(s) through upload button are working fine, but drag n drop not working. While doing drag and drop, the file is simply opening with browser.

Code: Latest ifm.php
Browser: Chrome 63.x
File(s) tried: PDF, JPEG, TXT

Good work ! Keep it up ! Congrats !

**Comment by misterunknown** [comment]
Indeed. I fixed that in the latest commit and deployed it to https://ifmdemo.misterunknown.de. I could test this only in FF 58 and Chrome 64 on Linux, but I guess on Windows it works as well. Let me know if it works for you.

**Comment by misterunknown** [comment]
I guess it works, so I close this issue.
