### ISSUE TITLE
File icon could be more precise

### ISSUE THREAD

**Issue by lovett** [misterunknown/ifm#92]
I saw in the demo that `newfile.txt` is displayed with the `icon-file-word` class, which seemed odd.

In `getTypeIcon()` there are are a few file extensions associated with `icon-file-word` that aren't associated with Word. I'd like to instead suggest using the generic `icon-doc` class for these, and only using `icon-file-word` for things that are genuinely Word files. The same goes for the excel and powerpoint icons. Otherwise the UI is slightly misleading.

Also, there may be a typo for the `dotx` case. The function matches the extension _do**t**x_ but perhaps you meant _do**c**x_

**Comment by misterunknown** [comment]
Good point, I changed that.
