### ISSUE TITLE
Upload Popup

### ISSUE THREAD

**Issue by exonas** [misterunknown/ifm#94]
Is it really important to show an extra pop up for upload? It would be much easier to upload file just by clicking on the upload button.

**Comment by misterunknown** [comment]
Well, I sometimes have to set a new filename when uploading a file, so I need the upload dialog. However, you can speed up the upload process by:

 * using keystrokes ( <kbd>u</kbd> for the upload dialog, <kbd>space</kbd> for the browser file dialog )
 * useing drag&drop from a file explorer

Does that suit your demands?

**Comment by exonas** [comment]
Thanks. Hopefully I am  not bothering..Is it possible to rename filename in place instead of showing pop up?

**Comment by misterunknown** [comment]
It would be generally possible to remove the upload file dialog, but I don't see a great improvement with that. What exactly is your use case? If you have many files to upload, you could do this, for example, with curl. I have some cases where I do something like that:
```bash
for i in *.zip
do
  curl "$IFM_URL" -F "api=upload" -F "dir=backup/custom/www" -F "file=@${i}"
done
```

**Comment by exonas** [comment]
I just want to use IFM more quickly. My 3 suggestions are:
1. Remove upload dialogue
2. Rename files in place instead loading pop up
3. After clicking on file/photo it opens in browser..that's great. But clicking outside of preview area it does not close. It would be great if it closes just by clicking right or left side black area

**Comment by misterunknown** [comment]
I thought a bit about that. Regarding points 1 and 2: I understand your point, but I don't really see the improvement to discard the upload dialog. I think the drag&drop feature provides a very fast way of uploading files, and as the upload dialog has an additional value for me, I'll keep it.

Regarding point 3: If you click on a file, it gets opened directly in the browser, and this behaviour can't be influenced by the IFM. Most browsers, however, implement a keystroke to go back ( <kbd>alt</kbd>+<kbd>←</kbd> ). Alternatively there are many plugins which provide mouse gestures to go back.

**Comment by exonas** [comment]
Drag and drop means I need to open my web browser and my desktop file browser side by side. In a 13 inch laptop I always use my browser in full screen mode. I think it's not for me.

By the way, you have done a great job. Do you have plans to include a login?

**Comment by exonas** [comment]
Also, do you have plans to add checkbox so that, I can select multiple files?

**Comment by misterunknown** [comment]
> Drag and drop means I need to open my web browser and my desktop file browser side by side. In a 13 inch laptop I always use my browser in full screen mode. I think it's not for me.

It is also possible to select multiple files in the upload dialog, and upload them all at once :wink: 

> Do you have plans to include a login?

Authentication is already implemented. Please see [authentication](https://github.com/misterunknown/ifm/wiki/Authentication).

> Also, do you have plans to add checkbox so that, I can select multiple files?

Multiselect is also implemented already. You can select files either by pressing <kbd>ctrl</kbd> + left mouse button, or you can highlight the item with the cursor keys and select them by pressing <kbd>space</kbd>.

**Comment by exonas** [comment]
Thanks a lot!

**Comment by exonas** [comment]
In the home page the "[up]" link has nothing to do. Is it possible to hide it in the home page?

**Comment by exonas** [comment]
Search only shows result with exact match. Is it possible to see results with partial matches?

**Comment by misterunknown** [comment]
> In the home page the "[up]" link has nothing to do. Is it possible to hide it in the home page?

The "[up]" entry has two tasks: First, it provides the ability to go up, and second, it provides the ability to download the entire directory as a zip. In the root_directory you can't go up, but the download button works and is still senseful.

**Comment by exonas** [comment]
Is it possible to configure IFM for multiple user? Each user should have their own directory under root directory. Maybe dynamically change root directory based on username?

**Comment by misterunknown** [comment]
> Is it possible to configure IFM for multiple user?

For multi-user please see #89. At the moment this is only possible via some tweaks (see [this](https://github.com/misterunknown/ifm/issues/89#issuecomment-365857096) comment).
