### ISSUE TITLE
Bulk delete files

### ISSUE THREAD

**Issue by pyyick** [misterunknown/ifm#96]
It's nice to have a bulk delete files function. When I have hundreds of files in the directory, it's a painful process to delete files.

**Comment by misterunknown** [comment]
You can select multiple files by either pressing <kbd>Ctrl</kbd> and left mouse click or by focus the files with the arrow keys (or <kbd>j</kbd> and <kbd>k</kbd>) and selecting them with <kbd>space</kbd>. Afterwards you can delete them by using the context menu or pressing <kbd>del</kbd>. See also [keybindings](https://github.com/misterunknown/ifm#key-bindings).

Is that suitable for you?

**Comment by misterunknown** [comment]
Can I close this?

**Comment by pyyick** [comment]
ok
