### ISSUE TITLE
I could only uoload the file size less than 1MB.  

### ISSUE THREAD

**Issue by Jupiterss** [misterunknown/ifm#98]
![qq 20180518155003](https://user-images.githubusercontent.com/8213282/40222862-88f9b156-5ab3-11e8-92a3-b989c1d432db.jpg)

**Comment by Jupiterss** [comment]
https://www.asuracrypt.cf/ @misterunknown

**Comment by misterunknown** [comment]
Check your PHP configuration for
* upload_max_filesize
* post_max_size

**Comment by misterunknown** [comment]
The progress bar only indicates the upload process itself. Sometimes the server-side processings take a bit longer, especially with very large files. Does the upload process finish after some time?

**Comment by Jupiterss** [comment]
I don't know if it's finished or not.......
I uploaded a mp3 format of 8MB size for several times.... It just kept uploading for no reason... and after the progress bar was gone,there's no file uploaded to be seen.

**Comment by Jupiterss** [comment]
Well..... I solved this problem afterwards.  It seems I have to use other browsers  to upload than Firefox.

**Comment by misterunknown** [comment]
Which version of firefox did you use? I just tested the file upload with firefox 59.0.2 and it worked fine. Any messages in the PHP error log?

**Comment by misterunknown** [comment]
I guess this can be closed.
