### ISSUE TITLE
Not all files are able to be edited

### ISSUE THREAD

**Issue by Jwink3101** [misterunknown/ifm#99]
For some reason, some files, including `*.txt` do not give me the ability to edit. But I do have `"edit" => 1,` and some files *do* still allow the edit

**Comment by misterunknown** [comment]
I determine the editability of a file on basis of the mime type. Could you execute these line with your problematic file and paste the output:
```php
<?php
echo mime_content_type( $filename );
```
Maybe the mime type is somehow weird.

**Comment by Jwink3101** [comment]
I’m sorry, I am a python noob. Can you hold my hand a bit more on what to do? Just put that in a php file and see what it says? Or run it in the terminal?

**Comment by misterunknown** [comment]
No problem. You can do it in two ways:

1. Via the PHP CLI. Just execute this command in a shell:
```bash
echo -e '<?php\necho mime_content_type("my_file.txt");' | php
```
Of course you have to substitute `my_file.txt` with your file.

2. Via a script. Just create a PHP file with the following content on your webspace:
```php
<?php
echo mime_content_type("my_file.txt");
```
Now you can call it via the webserver, for example `http://example.org/script.php`.

**Comment by misterunknown** [comment]
I just pushed an update, which allows to disable the mime_type detection (5138d82). Just turn on this option and you should be able to edit all files.

Nevertheless I'd like to know which MIME type your files was, so I can add it to the list of editable types.

**Comment by Jwink3101** [comment]
First of all, sorry for the slow update. I got slammed at work.

Second of all, thanks for being so responsive and awesome.

Third of all, running the mime script seemed to show the issue. It is coming up as a pgp-key. It is that (in base64 so *not* binary form) with some additional text I had written around it. I guess that is what messed it up. And it is what I was looking to edit so I could copy it sans download.

I seem to recall there being other files with the same issue but I can't see them know so I may be wrong.

Thanks!

**Comment by misterunknown** [comment]
> First of all, sorry for the slow update. I got slammed at work.

No problem :)

> Third of all, running the mime script seemed to show the issue. It is coming up as a pgp-key. It is that (in base64 so not binary form) with some additional text I had written around it. I guess that is what messed it up. And it is what I was looking to edit so I could copy it sans download.

Interesting. I'll add the non-binary PGP mime types to the list of editable types.

> I seem to recall there being other files with the same issue but I can't see them know so I may be wrong.

If you find any other mime types which are uneditable, just let me know ;)
